### ISSUE TITLE
TPM rng device results disabled also if is present.

### ISSUE THREAD

**Issue by MR-Diamond** [nhorman/rng-tools#104]
CPU:
`Intel Core i5-3210M`

`lsmod | grep rng`:
`tpm_tis,tpm_infineon,tpm_rng,tpm_tis_core`

`lscpu | grep -o -a -m 1 -h rdrand`:
`rdrand`

/dev/tpm0 and /dev/hwrng are present.

Then I run:
`rngd --rng-device=/dev/hwrng -f`:
```
Initializing available sources
[hwrng ]: Initialized
[rdrand]: Enabling RDRAND rng support
[rdrand]: Initialized
[jitter]: Initializing AES buffer
[jitter]: Unable to obtain AES key, disabling AES in JITTER source
[jitter]: Enabling JITTER rng support
[jitter]: Initialized
[pkcs11]: PKCS11 Engine /usr/lib64/opensc-pkcs11.so Error: No such file or directory
[pkcs11]: Initialization Failed
[rtlsdr]: Initialization Failed
```

And as I run `rngd -l` I got:
Entropy sources that are available but disabled
```
1: TPM RNG Device (tpm)
4: NIST Network Entropy Beacon (nist)
Available and enabled entropy sources:
2: Intel RDRAND Instruction RNG (rdrand)
5: JITTER Entropy generator (jitter)
```

Why TPM is listed ad disabled?
Am I miss something?

**EDIT**

Despite the fact that rng-tools reports tpm as available but disabled, I hower tried:
As I rebooted,  the sytemd unit `systemd-random-seed.service` tooked about three seconds; without TPM but with only  rdrand of the CPU, instead, `systemd-random-seed.service` tooked 430ms.
So, maybe, TPM is not reliable?
But remains the question why is reported as present but disabled.

**Comment by nhorman** [comment]
yes, in newer kernels (don't have the exact kernel version in front of me), tpms feed entropy to userspace directly through /dev/hwrng.  As such, the tpm device entropy source has been moved from default enabled to default disabled.  You can re-enable it manually with the -n tpm argument on older kernels, but you shouldn't need to, since you get the entropy from /dev/hwrng now
