### ISSUE TITLE
jitterentropy was chosen though hwrng is available

### ISSUE THREAD

**Issue by yegorich** [nhorman/rng-tools#109]
rng-tools v6.10. Though `rngd --list` shows both hwrng and jitter, only jitter calls will be made to get entropy. Only after disabling the jitter dependency during the configuration step, I could successfully use the hwrng from OMAP3 (am335x SoC), linux kernel 5.4.x.

Any idea why I am observing such behaviour?

**Comment by nhorman** [comment]
That should actually happen the other way around.  rngd should be prioritizing fast entropy sources (like /dev/hwrng) over slower sources like jitterentropy when the former is available.  What you're seeing suggests that /dev/hwrng is not returning entropy when its started.  Can you run rngd with -d and provide the output log for analysis?

**Comment by yegorich** [comment]
```
# rngd -d -f
Initializing available sources
[hwrng ]: Initialized
[jitter]: Limiting thread count to 1 active cpus
[jitter]: JITTER starts 1 threads
[jitter]: CPU Thread 0 is ready
[jitter]: Initializing AES buffer
[jitter]: xread_jitter requests 16 bytes from pipe
[jitter]: failed read: Resource temporarily unavailable
[jitter]: xread_jitter requests 16 bytes from pipe
[jitter]: failed read: Resource temporarily unavailable
[jitter]: Unable to obtain AES key, disabling AES in JITTER source
[jitter]: xread_jitter requests 16535 bytes from pipe
[jitter]: failed read: Resource temporarily unavailable
[jitter]: xread_jitter requests 16535 bytes from pipe
[jitter]: failed read: Resource temporarily unavailable
[jitter]: Enabling JITTER rng support
[jitter]: xread_jitter requests 4 bytes from pipe
[jitter]: failed read: Resource temporarily unavailable
[jitter]: xread_jitter requests 4 bytes from pipe
[jitter]: failed read: Resource temporarily unavailable
[jitter]: xread_jitter requests 4 bytes from pipe
[jitter]: failed read: Resource temporarily unavailable
[jitter]: xread_jitter requests 4 bytes from pipe
[jitter]: failed read: Resource temporarily unavailable
[jitter]: Initialized
Reading entropy from Hardware RNG Device
[jitter]: JITTER thread on cpu 0 wakes up for refill
Added 4041/4096 bits entropy
Pool full at 4096, sleeping!
[jitter]: jent_read_entropy time on cpu 0 is 2.530203408700e+01 sec
[jitter]: Writing to pipe
[jitter]: DONE Writing to pipe with return 16535
[jitter]: JITTER thread on cpu 0 wakes up for refill
```

**Comment by nhorman** [comment]
That looks pretty normal.  It shows that Hwang initialized, as did jitter (which always takes a long time, due to how it works). But no entropy was every requested after init, so no sources are actually being read from.post init.  If you, in another window run:
Cat /dev/random

You should see that rings queries the hwrng for entropy

**Comment by yegorich** [comment]
My problem is that with jitter enabled, `rngd` consumes 99% of CPU for about a minute and this increases the boot time. It would be great if the most efficient engine would be initialized and only if it fails then fall back to the next one.

**Comment by nhorman** [comment]
I understand that, and once all the entropy sources are initialized, thats what will happen.  But to get to that point you need to initialize all the entropy sources, and if on your system it takes jitter a minute to obtain enough entropy to pass the initial fips test, thats what you have to live with.  If you want to avoid that, you can run rngd with the -x jitter option, to disable jitterentropy. If you have a hwrng available (as it appears you do), then that shouldn't be problematic, as you will have plenty of entropy from that source.

**Comment by yegorich** [comment]
I have overlooked the `-x` parameter. This solves my problem. Thanks.
