### ISSUE TITLE
rngd.c: Need to include <limits.h> to compile with musl

### ISSUE THREAD

**Issue by lonwillett** [nhorman/rng-tools#11]
In order to compile with the musl c library, <limits.h> needs to be included by rngd.c. This should be a harmless enough change.

**Comment by nhorman** [comment]
I'm not opposed,but can you post the error here?  I'm curious to know what symboly is missing that requires limits.h in rngd

**Comment by lonwillett** [comment]
LONG_MAX isn't defined:

cc -DHAVE_CONFIG_H -I.     -specs=/void-packages/common/environment/configure/gccspecs/hardened-cc1  -fstack-protector-strong -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe    -MT rngd.o -MD -MP -MF .deps/rngd.Tpo -c -o rngd.o rngd.c
rngd.c: In function 'parse_opt':
rngd.c:193:15: error: 'LONG_MAX' undeclared (first use in this function)
   if ((idx == LONG_MAX) || (idx > ENT_MAX)) {
               ^~~~~~~~
rngd.c:193:15: note: each undeclared identifier is reported only once for each function it appears in

**Comment by nhorman** [comment]
resolved in commit d91bf8b856a7ef4e0c1418ccbec0343102915af0
