### ISSUE TITLE
Jitter & AES

### ISSUE THREAD

**Issue by wrightleft** [nhorman/rng-tools#111]
I'm using rngd on an embedded device because it generates very little entropy on its own. When starting up the rngd daemon will block for a long time in initializing the AES key and initial vector. Which makes sense, because there is no entropy to generate those.

Is this the intended behavior? It seems odd for rngd, a daemon that exists to generate entropy, to require entropy during initialization. Could the AES key and initial vector initialization be deferred until the rest of the rngd daemon is running and generating entropy? Thus, solving the chicken-and-egg problem?

**Comment by nhorman** [comment]
Nominally, its.not a problem.because we can get enough entropy.from.other sources (like the tpm), to do this unit quickly,  but on an embedded system that could become problematic.   In those cases the recommendation is to disable aes grooming with the ringds -o option. We can look at deferring the need for entropy, but that becomes rather tricky, and may not.help.that much (jitter takes significant time.on small.systrms to.generate entropy regardless.of.aes usage)

**Comment by nhorman** [comment]
https://github.com/nhorman/rng-tools/tree/multi-state-init

You're welcome to try that branch out.  It uses stack garbage to create a initial aes key and iv.  I'm working on adding a re-key threshold that will kick in once we've generated some initial entropy.  It may help, but fair warning, if jitter is your only entropy source, it may not help much, as smaller embedded systems have more predictable timing on loads and stores, which will cause jitter to delay when generating entropy.  But please give it a shot, if it helps I'll merge it.

**Comment by wrightleft** [comment]
> Nominally, it's not a problem because we can get enough entropy from other sources (like the tpm), to do this unit quickly.

The device does have a TPM available, and rngd does use it, but it doesn't seem to use it as part of jitter initialization. That's why I was thinking of deferring the AES key and initial vector until later, when the TPM has been initialized.

I did disable the AES generation as part of the jitter options and that works well. I just wanted to know if I understand the problem correctly.

**Comment by nhorman** [comment]
You do understand the issue correctly,and you are also right in that each
entropy source only uses itself to init the aes key and if to avoid a bunch
of recursive init issues.  Did you try the branch I provided to you?
Best
Neil

**Comment by wrightleft** [comment]
We are happy with disabling AES in the jitter options for now, so I won't have time to test anything out right now. Sorry.

**Comment by nhorman** [comment]
Ok, reopen if you get time to test
