### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by dermotbradley** [nhorman/rng-tools#112]
Hi

It has been 9 months since the last release and there have been quite a number of important fixes/changes since then.

Could you publish a 6.11 release soon?

Thanks in advance

**Comment by nhorman** [comment]
Sure, I'll take care of it in the morning

**Comment by dermotbradley** [comment]
Thanks.

Just to point out I've raised a separate Issue, #113, regarding a patch currently being used by Alpine Linux - not sure if its still relevant, if so I guess it should be upstreamed.

**Comment by nhorman** [comment]
done
