### ISSUE TITLE
rdrand_asm.S patch relevant?

### ISSUE THREAD

**Issue by dermotbradley** [nhorman/rng-tools#113]
Hi

Whilst looking at updating Alpine Linux's package of rng-tools to the new 6.11 release (once you get it out, no pressure!) I noticed 1 existing patch that is not in your Git tree. However there's no comments with the patch to understand if its still relevant, perhaps the filename give you an idea of its purpose?

The patch is here: https://git.alpinelinux.org/aports/tree/main/rng-tools/fix-textrels-on-PIC-x86.patch

Should this be upstreamed? If so, could this be done before the new release?

**Comment by nhorman** [comment]
Its already been incorporated as commit c58dd184c87b326999f62e6de0842a30897cf57c
