### ISSUE TITLE
v6.10 -> V6.11: is "v" capitalization going to be permanent in git tag?

### ISSUE THREAD

**Issue by realnickel** [nhorman/rng-tools#114]
Hello!
Subj kinda breaks some of our packaging automation, so I'm wondering whether I should make an exception for this release only, or should permanently change scripts for future releases also.

**Comment by nhorman** [comment]
crap, apologies, that was an error on my part.  Would it be acceptable to you if I added another tag at the same commit with a lower case v?  I'm not planning on changing the format at all.

**Comment by realnickel** [comment]
Yes, adding one more tag would be sufficient. Thank you for a rapid reply!

**Comment by nhorman** [comment]
I'm away from a computer right now, but I'll get to it this
weekend...monday at the latest.  Sorry about that!
Neil

**Comment by nhorman** [comment]
Corrected tag added with lowercase v.  Thanks!

**Comment by realnickel** [comment]
Thank you!
