### ISSUE TITLE
jitter source makes rngd hangs at 100% cpu usage

### ISSUE THREAD

**Issue by xse** [nhorman/rng-tools#117]
Hello,
A recent update of rng-tools introduced a 100% CPU usage from rngd, this is related to that jitter source and `rngd -f -x jitter` fixes the issue.
I'm using a raspberry pi (armv6) machine running archlinuxarm, the same issue has been reported on raspberry pi zero, 1b, 3b and 4.

An strace leads to believe that rngd gets stuck in an endless loop of `clock_gettime64` which does not happen when `-x jitter` is used.

Here's a sample strace output:
```
write(2, "Initializing available sources\n", 31Initializing available sources
) = 31
openat(AT_FDCWD, "/dev/hwrng", O_RDONLY|O_NOCTTY) = 3
read(3, "\23IJ4\255\330\340\312z\tn\367&\270g\243", 16) = 16
read(3, "Nc)`", 4)                      = 4
read(3, "\347\3\270\334", 4)            = 4
write(2, "[hwrng ]: Initialized\n", 22[hwrng ]: Initialized
) = 22
rt_sigaction(SIGUSR1, {sa_handler=0x46a7e0, sa_mask=[USR1], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x76b02120}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
openat(AT_FDCWD, "/proc/sys/crypto/fips_enabled", O_RDONLY) = -1 ENOENT (No such file or directory)
clock_gettime64(CLOCK_REALTIME, {tv_sec=1610569934, tv_nsec=579021205}) = 0
clock_gettime64(CLOCK_REALTIME, {tv_sec=1610569934, tv_nsec=581817181}) = 0
clock_gettime64(CLOCK_REALTIME, {tv_sec=1610569934, tv_nsec=583609165}) = 0
... (gets stuck doing endless clock_gettime64)
```

The same thing arise when using `rngd --list` where the program gets stuck mid list and has to be killed.
I'm afraid i can't give you much details, `--debug` doesn't give any useful information and there isn't anything useful in the logs.
I'm not confident in my capacity to pinpoint and tell you exactly where the problem is, but i'mhappy to assist however i can if you need more information, i'm willing to try anything and/or give you an ssh access to somewhere where you could replicate the issue.

Have a good day!

**Comment by nhorman** [comment]
Thats less getting stuck in a loop so much as it is the jitterentropy source doing what its supposed to do.  Jitter gathers entropy by measuring the change in the time it takes for load store operations to complete.  That in turn requires lots (LOTS) of calls to clock_gettime64.   Theres unfortunately no way around that for that entropy source.   On the upside, IIRC all rasberry pi's have a hwrng device that you can use to pull entropy much more quickly from.  Jitter is really meant to be an entropy source used in situations in which no other source is available (think vm's without any virt-rng device).  On your platoform, just disabling jitter (or not even compiling it in), would be the recommended solution

**Comment by xse** [comment]
Oh that makes sense, yeah i once let it run for at least 20 minutes just to see if it would get unstuck without success so i assumed it was stuck, I'll just force the `-x jitter` everywhere, thanks a lot!

**Comment by dermotbradley** [comment]
@xse I tested this with a RPI 3B running Alpine Linux aarch64, I have not yet tested armv7.

I tested 2 scenarios: (a) with both hwrng and jitter enabled, and (b) with only jitter enabled.

In both cases I logged in as quickly as possible after boot and ran "htop" - I could see rngd using approx. 50% of CPU but only for approx. 30-40 seconds and then the CPU returned to idle.

So there's doesn't appear to be fundamental problem with using jitter only on an RPI. Obviously the CPU usage will vary with model (i.e. I'd expect a Zero and a RPI/RPI2 to use a bit more than a RPI 3). Its possible that the behaviour on 32bit OS (i.e. armv7) might different from 64bit OS (aarch64) as well.

**Comment by xse** [comment]
@dermotbradley that quickly ? damn i know my rpi 1b+ is slow but still if it takes you 40s at most i'd expect mine to be able to do it even if it takes 5 minutes.

Here's a screenshot 30+ minutes after a reboot when i disable `-x jitter` along with cpuinfo, uname & so on, still stuck on `Initializing AES buffer`:
![2021-01-22 16_21_18-xse@buttplug_ tmux](https://user-images.githubusercontent.com/183953/105509594-f1389380-5ccd-11eb-8355-a4c780d960f6.png)

I'm gonna let it run for a bit just to see if it ever manages to go down.

**Comment by Mingli-Yu** [comment]
@nhorman,
In my system, only jitter can be used, could you help to guide how to address the 100% cpu issue? Thanks  a lot!

**Comment by nhorman** [comment]
@dermotbradley, something is odd about your setup.  When you run with -x jitter, you shouldn't see messages about the jitter entropy source initalizing, so it seems like you're still getting the cpu usage that you might expect if jitter was enabled.  can you build without jitterentropy enabled (ie. configure --disable-jitterentropy) and see if the problem subsides?  You might have an issue with simply not being able to disable an entropy source

@Mingli-Yu Theres nothing you can do, if you're only source of entropy is jitter, then you're at the mercy of how variant the timing of your cpu is, which in and of itself is very cpu intensive.  Thats by design, because non-intensive cpu loads don't introduce a lot of timing variance.

**Comment by dermotbradley** [comment]
> @dermotbradley, something is odd about your setup.

I think you're getting me confused with @xse, I'm having no problems.

**Comment by Mingli-Yu** [comment]
@nhorman,
Thanks you! 
If so, it's better only call jitter entropy source if no other entropy source available as  https://github.com/nhorman/rng-tools/pull/122
