### ISSUE TITLE
tag problems

### ISSUE THREAD

**Issue by Neustradamus** [nhorman/rng-tools#119]
Dear @nhorman,

I see:
- https://github.com/nhorman/rng-tools/releases/tag/V6.11

And:
- https://github.com/nhorman/rng-tools/releases/tag/show
- https://github.com/nhorman/rng-tools/releases/tag/v6.11

Can you remove 2 bad tags?

**Comment by nhorman** [comment]
I'm not sure why I would remove them.  The two erroneous tags aren't hurting anything,  you can just ignore them,and others might be using them at this point (incorrectly of course), but I dont want to break them

**Comment by Neustradamus** [comment]
@nhorman: The only good is:
- https://github.com/nhorman/rng-tools/releases/tag/V6.11

On https://github.com/nhorman/rng-tools/:
```
"Releases" (16)
rng-tools 6.11 bug fix update (Latest)
on 8 Jan
+ 15 releases
```

On https://github.com/nhorman/rng-tools/releases:
```
(Latest release)
V6.11
2ea1347
```

**Comment by nhorman** [comment]
I think your not getting my point.  I could remove the erroneous tags, but doing so might break people using them, and it doesn't hurt anyone not using them
