### ISSUE TITLE
rtlsdr disabled by default

### ISSUE THREAD

**Issue by jpalus** [nhorman/rng-tools#125]
Current help is somewhat confusing -- it suggests `--without-rtlsdr` to disable rtlsdr while in practice it is already default behavior:
https://github.com/nhorman/rng-tools/blob/54c9139b328203c4b8c014039e581fc461628b4e/configure.ac#L44-L49
Either `with_rtlsdr` should be set to `check` instead of `no` like in other flags (and I think that was the intention) or option should be updated.

**Comment by nhorman** [comment]
wanna send a patch? Im a bit busy today.
