### ISSUE TITLE
Problem compiling rng-tools 6.13 on Alpine

### ISSUE THREAD

**Issue by dermotbradley** [nhorman/rng-tools#139]
Hi, I'm the Alpine package maintainer for rng-tools and jitterentropy-library.

I've just packaged up rng-tools 6.13 and the compile is failing as follows:

```
rngd_jitter.c:70:2: warning: implicit declaration of function 'pthread_attr_seta
ffinity_np'; did you mean 'pthread_setaffinity_np'? [-Wimplicit-function-declara
tion]
   70 |  pthread_attr_setaffinity_np(&thread_ctx->notime_pthread_attr, cpusize, 
cpus);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |  pthread_setaffinity_np
...
...
...
gcc  -I/usr/include/ -I/usr/include/libusb-1.0     -I/usr/include/libxml2   -pth
read -Os -fomit-frame-pointer -pthread  -Wl,--as-needed,-O1,--sort-common -o rng
d rngd-rngd.o rngd-rngd_entsource.o rngd-rngd_linux.o rngd-util.o rngd-ossl_help
ers.o rngd-rngd_nistbeacon.o rngd-rngd_rdrand.o rdrand_asm.o   rngd-rngd_jitter.o rngd-rngd_rtlsdr.o  librngd.a -ljitterentropy -largp -lrtlsdr -lusb-1.0    -ljansson  -lcurl  -lxml2  -lssl -lcrypto   -ljitterentropy -largp
/usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: rngd-rngd_jitter.o: in function `rngd_notime_start':
rngd_jitter.c:(.text+0x9de): undefined reference to `pthread_attr_setaffinity_np'
collect2: error: ld returned 1 exit status
make: *** [Makefile:630: rngd] Error 1
```

So it appears that pthread_attr_setaffinity_np does not exist in the MUSL C library, it appears to a GLIBC-ism. I found another unrelated project which fixed the same issue (https://github.com/awslabs/aws-c-common/pull/766/files) by using pthread_setaffinity_np for both MUSL and BSD systems.

**Comment by nhorman** [comment]
https://github.com/nhorman/rng-tools/tree/setaffinity

Try that branch, it should select the appropriate setaffinity call based on availability as determined in the configure script

**Comment by dermotbradley** [comment]
> Try that branch, it should select the appropriate setaffinity call based on availability as determined in the configure script

That compiled fine. I'll do some testing with both x86_64 and aarch64.

Thanks

**Comment by nhorman** [comment]
please do, and report back here.  If it works on both arches for you, I'll merge it asap

**Comment by nhorman** [comment]
any test results?

**Comment by dermotbradley** [comment]
Hi. Sorry for the delay in getting back to you.

I've tested rng-tools 6.14 (with the 2 comits from your setaffinity branch) together with jitterentropy-library 3.1.0 on x86_64 and it seems fine.

I haven't yet had a chance to test aarch64 unfortunately, but I don't expect any issues.

FYI the x86_64 testing was with a single-core Sempron and rngd used 100% CPU for approx 30 seconds at startup, I guess this would be exercising your recent "onecpu" code changes.

**Comment by nhorman** [comment]
ok, I've merged the branch, I'm going to close this, since you seem confident its all working.  please reopen if you encounter any problems
