### ISSUE TITLE
configure detects pkcs11 engine in wrong path

### ISSUE THREAD

**Issue by ptiggerdine** [nhorman/rng-tools#153]
Description:
Autoconf detects pkcs11 engine in the /usr/lib64/ rather than /usr/lib.
Steps to reproduce:
1. use a raspberry pi zero w
2. git clone repo
3. installed dependencies to build including opensc-pkcs11-dev libraries
4. run ./autogen.sh
5. run ./configure
6. check Makefile or config.log for PKCS11_ENGINE location
Expected outcome:
Makefile/config.log should detect pkcs11 engine in /usr/lib

**Comment by nhorman** [comment]
please attach your config.log

**Comment by ptiggerdine** [comment]
As requested.

[config.log](https://github.com/nhorman/rng-tools/files/7712051/config.log)

**Comment by nhorman** [comment]
thank you, please try building with the branch in this PR:
https://github.com/nhorman/rng-tools/pull/154

It should fix your issue

**Comment by ptiggerdine** [comment]
as mentioned in the code comment, The fix worked abiet for a path change for the opensc-pkcs11 lib to /usr/lib/arm-linux-gnueabihf

**Comment by nhorman** [comment]
yeah, per note in PR (which is now merged based on your testing), if you want to set a non-standard path, you can do so at build time, like this:
make PKCS11_ENGINE=/usr/lib/arm-linux-gnueabihf/lib
