### ISSUE TITLE
Request new release of rng-tools including jitter-moreentropy branch changes

### ISSUE THREAD

**Issue by dermotbradley** [nhorman/rng-tools#155]
Hi

There has not been a rng-tools release since 9th August but there have been a handful or so of additional changes merged to master.

Also during the discussion/diagnosis of #150 you asked me to try the jitter-moreentropy branch, which I did. Is there any intention to merge those changes into Master? I have been including the 2 changes from that branch in the version of rng-tools I maintain for Alpine Linux.

I'd like to move to an official version that contains all the Master changes plus the jitter-moreentropy changes.

Also, as part of #150, at the time you had said "_Its going to take me a bit to figure out the best way to codify the new jitter features as options that are reasonably configurable to a user_", did anything come of this?

**Comment by nhorman** [comment]
6.15 released here
https://github.com/nhorman/rng-tools/releases/tag/v6.15

**Comment by nhorman** [comment]
IIRC, from the conversation we had in #150 they didn't make much difference to your performance, so I would say no
