### ISSUE TITLE
Is rngd_rndr using correct rng_options index?

### ISSUE THREAD

**Issue by dermotbradley** [nhorman/rng-tools#161]
Currently the following lines use DARN_OPT_AES as the index:

https://github.com/nhorman/rng-tools/blob/master/rngd_rndr.c#L174
https://github.com/nhorman/rng-tools/blob/master/rngd_rndr.c#L190

Is this correct? Shouldn't it be DRNG_OPT_AES instread? Especially as .rng_options for rndr points to drng_options:

https://github.com/nhorman/rng-tools/blob/master/rngd.c#L358

**Comment by nhorman** [comment]
you're right.  It just so happens to work out since DRNG_OPT_AES == DARN_OPT_AES, but DRNG_OPT_AES is the right one to use.  I'll fix it.  Thanks!

**Comment by nhorman** [comment]
fixed with commit 6e1a11ae6df8cd6c98657a8b78761763f3ff2abd
