### ISSUE TITLE
v6.15 build fails with jitterentropy 3.4

### ISSUE THREAD

**Issue by rezso** [nhorman/rng-tools#162]
I can compile rng-tools 6.15 with jitterentropy 3.3.1, but with 3.4.0 fails:

`rngd_jitter.c: In function ‘rngd_notime_start’:
rngd_jitter.c:56:38: error: invalid use of undefined type ‘struct jent_notime_ctx’
   56 |  ret = -pthread_attr_init(&thread_ctx->notime_pthread_attr);
      |                                      ^~
rngd_jitter.c:79:41: error: invalid use of undefined type ‘struct jent_notime_ctx’
   79 |  pthread_attr_setaffinity_np(&thread_ctx->notime_pthread_attr, cpusize, cpus);
      |                                         ^~
rngd_jitter.c:81:35: error: invalid use of undefined type ‘struct jent_notime_ctx’
   81 |  ret = -pthread_create(&thread_ctx->notime_thread_id,
      |                                   ^~
rngd_jitter.c:82:16: error: invalid use of undefined type ‘struct jent_notime_ctx’
   82 |     &thread_ctx->notime_pthread_attr,
      |                ^~
rngd_jitter.c: In function ‘rngd_notime_stop’:
rngd_jitter.c:97:25: error: invalid use of undefined type ‘struct jent_notime_ctx’
   97 |  pthread_join(thread_ctx->notime_thread_id, NULL);
      |                         ^~
rngd_jitter.c:98:34: error: invalid use of undefined type ‘struct jent_notime_ctx’
   98 |  pthread_attr_destroy(&thread_ctx->notime_pthread_attr);
      |                                  ^~
make[2]: *** [Makefile:821: rngd-rngd_jitter.o] Error 1`

**Comment by nhorman** [comment]
I can fix it.  In the interim, you need to build jitterentropy with JENT_CONF_ENABLE_INTERNAL_TIMER, so that struct gets defined

**Comment by nhorman** [comment]
https://github.com/nhorman/rng-tools/pull/163

Opened that PR, Can you test with that branch and let me know if it works for you?

**Comment by rezso** [comment]
#163 works for me. Thanks.

**Comment by nhorman** [comment]
https://github.com/nhorman/rng-tools/pull/163
resolved
