### ISSUE TITLE
rngtestjitter.sh failures after recent changes

### ISSUE THREAD

**Issue by sharkcz** [nhorman/rng-tools#174]
I am seeing rngtestjitter.sh failures on various platforms in our CI after recent changes (last batch of commits). 
````
[jenkins@ibm-p8-generic-02-guest02 ppc64le]$ cat tests/test-suite.log
==========================================
   rng-tools 6.15: tests/test-suite.log
==========================================

# TOTAL: 3
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: rngtestjitter.sh
======================

Disabling 0: Hardware RNG Device (hwrng)
Disabling 2: Intel RDRAND Instruction RNG (rdrand)
Disabling 1: TPM RNG Device (tpm)
Initializing available sources
[darn  ]: No HW SUPPORT
[darn  ]: Initialization Failed
[jitter]: Initializing AES buffer
[jitter]: Enabling JITTER rng support
[jitter]: Initialized
[pkcs11]: No pkcs11 slots available
[pkcs11]: Initialization Failed
[rtlsdr]: Initialization Failed
unable to adjust write_wakeup_threshold: Permission denied
rngtest: bits received from input: 2000064
rngtest: bits sent to output: 1980000
rngtest: FIPS 140-2 successes: 99
rngtest: FIPS 140-2 failures: 1
rngtest: FIPS 140-2(2001-10-10) Monobit: 0
rngtest: FIPS 140-2(2001-10-10) Poker: 0
rngtest: FIPS 140-2(2001-10-10) Runs: 1
rngtest: FIPS 140-2(2001-10-10) Long run: 0
rngtest: FIPS 140-2(2001-10-10) Continuous run: 0
rngtest: input channel speed: (min=847.269; avg=78187.550; max=19531250.000)Kibits/s
rngtest: FIPS tests speed: (min=126.314; avg=128.632; max=129.752)Mibits/s
rngtest: output channel speed: (min=1.552; avg=23.342; max=18.626)Gibits/s
rngtest: Program run time: 11832646 microseconds
killing
FAIL rngtestjitter.sh (exit status: 1)
````
Looks to me the 15 sec timeout needs to be extended. 30 secs seems to be a good value, the test passes consistently (on a Power8 system).

But on a aarch64 system (APM Mustang) I still seeing failures
````
[jenkins@apm-mustang-ev3-05 aarch64]$ cat tests/test-suite.log
==========================================
   rng-tools 6.15: tests/test-suite.log
==========================================

# TOTAL: 3
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: rngtestjitter.sh
======================

Disabling 0: Hardware RNG Device (hwrng)
Disabling 2: Intel RDRAND Instruction RNG (rdrand)
Disabling 1: TPM RNG Device (tpm)
Initializing available sources
[rndr  ]: No HW SUPPORT
[rndr  ]: Initialization Failed
[jitter]: Initializing AES buffer
[jitter]: Unable to obtain AES key, disabling JITTER source
[jitter]: Initialization Failed
[pkcs11]: No pkcs11 slots available
[pkcs11]: Initialization Failed
[rtlsdr]: Initialization Failed
Can't open any entropy source
Maybe RNG device modules are not loaded
FAIL rngtestjitter.sh (exit status: 1)

[jenkins@apm-mustang-ev3-05 aarch64]$ lsmod | grep rng
xgene_rng              20480  0
````

**Comment by nhorman** [comment]
sounds reasonable, if you want to send a PR, I'll merge it.

**Comment by sharkcz** [comment]
> sounds reasonable, if you want to send a PR, I'll merge it.

yup, will send you a PR

Any idea about the aarch64 issue? It is passing at commit 1871879e1f6909ae98f12535715004de54107d69, I guess I will bisect ...

**Comment by nhorman** [comment]
Re PR: Thanks
RE aarch64: hmm, I would have thought you would have rndr support by default there.  The error message your seeing indicates that HWCAP2_RNG isn't set in the AT_HWCAP2 register though, so I guess not

The loading of the xgene_rng module suggests you should have hwrng support.  Usually when you load hwsupport like that, and it doesn't show up, the first thing I check is the files in /sys/class/misc/hw_random to ensure the proper (or a) hwrng is selected.  doesn't seem likely it wouldn't but perhaps aarch64 is doing something odd

**Comment by sharkcz** [comment]
In addition to the aarch64 failure I am seeing this on s390x as well. At least on my CI machines, but it is consistent and bisecting points to commit c29424f10a0dcbd18ac25607fa1c81c18a960e81 ...

**Comment by sharkcz** [comment]
> what version of libjitterentropy are you building with on s390 and aarch64?

jitterentropy-3.4.0-2.fc36.s390x
jitterentropy-3.4.0-2.fc36.aarch64
jitterentropy-3.3.1-1.fc35.aarch64 (before upgrading to F-36)

**Comment by nhorman** [comment]
can you add -d to that, so we get debug output.  Seems like the jitter pool just is not obtaining entropy on this arch, but I'd like to be sure

**Comment by nhorman** [comment]
yeah, that looks like the read of the pipe that the jitter threads fill is detecting that the pipe is empty (i.e. the jitter threads are still trying to gather entropy.

I'm not really sure what to do here.  I just went through a issue in which people were complaining that jitter was blocking the startup of rngd for huge amounts of time because their platform didn't have great jitter variance, so we changed it to this mechanism, in which if it takes "too long" for some definition thereof (currently 5 seconds), we mark jitter as non-functional.  Which is exactly what  you are seeing here.

Thoughs on how to handle it? I can increase the timeout, or make it configurable, but at some point we need to either block indefinitely (angering people who want a  fast startup), or assume that after some reasonable time, jitter just isn't appropriate for the given platform

**Comment by sharkcz** [comment]
Thanks for the background info, it makes sense. I think part of my problem is that we run the build and tests as a regular user, which doesn't have access to `/devhwrng`.

What would work for me and perhaps for other people too would be moving the hard-coded 5 seconds timeout to a value that could be overridden by an environment variable for example. Seems in my case ~7s would be sufficient :-)

**Comment by sharkcz** [comment]
And just to be sure, isn't the configure logic for `HAVE_JITTER_NOTIME` inverted?

**Comment by nhorman** [comment]
configurable timeout: yeah, I'm on board with that.  Do you have cycles to implement that, or shall I take care of it?

NOTIME: Hmm, yeah, it might be inverted.  If you're building with the latest library, it should be set.  Not sure why that would be happening though.  I'll look into it futhrer

**Comment by sharkcz** [comment]
I am off next week, but I will be able to look at the timeout later then.

**Comment by nhorman** [comment]
cool, If I get the cycles I'll try poke at this some more next week

**Comment by nhorman** [comment]
I believe this is resolved now, please re-open if problems persist

**Comment by sharkcz** [comment]
Yup, it should be. I have updated the CI job, so let's wait for the next run :-)

**Comment by fuanan-3** [comment]
@all
In v6.16,I noticed that it still exists: FAIL: rngtestjitter.sh

**Comment by matoro** [comment]
I am also seeing this on sparc:
```
[jitter]: xread_jitter requests 16 bytes from pipe
[jitter]: failed read: Resource temporarily unavailable
```
until jitter source is disabled and test fails.

**Comment by matoro** [comment]
> I am also seeing this on sparc:
> 
> ```
> [jitter]: xread_jitter requests 16 bytes from pipe
> [jitter]: failed read: Resource temporarily unavailable
> [jitter]: Unable to obtain AES key, disabling JITTER source
> ```
> 
> until jitter source is disabled and test fails.

Scratch that, I was able to work around this with two changes:
```
sed -i 's/sleep 30/sleep 120/g' tests/rngtestjitter.sh
export RNGD_JITTER_TIMEOUT=90
```
