### ISSUE TITLE
Add mention of kernel version when referring to it in documentation

### ISSUE THREAD

**Issue by Ricky-Tigg** [nhorman/rng-tools#185]
**kernel v.:** 6.0 | **distribution:** Fedora |**rng-tools v.:** 6.15

Hello. As per the documentation via `man 8 rngd` is stated _For newer kernels which support non-blocking entropy pools_. That is the kind of sentence that invites reader to investigate whether the currently running kernel is to be considered as newer. Once done, i could conclude that it has to be [referring](https://github.com/torvalds/linux/commit/30c08efec8884fb106b8e57094baa51bb4c44e32) to the **version 5.6**, which is when the change was introduced. That would be well appropriated to mention it. I noted that same version also [introduced](https://github.com/torvalds/linux/commit/3f2dc2798b81531fd93a3b9b7c39da47ec689e55) _jitter_; that is an other story though.

**Comment by nhorman** [comment]
sure, patches welcome

**Comment by Ricky-Tigg** [comment]
Correct me if i am wrong; i interpreted _patch_ as _suggestion_. Here is one: _For kernels that support non-blocking entropy pools, which was introduced in version 5.6, it ..._

**Comment by nhorman** [comment]
No, please interpret patch as," please propose the change as a PR"

**Comment by nhorman** [comment]
you're not qualified to change the language in a man page?  Its just a text file....

**Comment by Ricky-Tigg** [comment]
In the surroundings either, no one is. A file! What file? Do we even know how to guess its name? Not to say how make that _PR_?

**Comment by Ricky-Tigg** [comment]
In the surroundings either, no one is. A file! What file? Do we even know how to guess its name? Not to say how to make that _PR_?
