### ISSUE TITLE
External tool as entropy source for Jetson devices

### ISSUE THREAD

**Issue by rgov** [nhorman/rng-tools#187]
Some Nvidia Jetson devices have a HWRNG but it is not exposed as a character device like `/dev/hwrng`. Instead, from userland you need to communicate with an agent running in a trusted computing environment. Nvidia provides a tool for doing so in the `nvidia-l4t-tools` package called `nvhwkey-app` that takes a number of bytes and outputs the random value in hexadecimal (to stderr, weirdly):

```
$ sudo /usr/sbin/nvhwkey-app -r 4  2>&1
5894002c
```

It would be nice if `rngd` could use this tool (or other external tools) as an entropy source.

**Comment by nhorman** [comment]
Whats the request here? 

I'm not inclined to support a non open tool as an entropy source, and honestly, from what you've said here, I don't see that I would have to do anything anyway.  If you want to use it just run it like this:

$ cat create_real_ent_src.sh
#!/bin/bash
mkfifo /dev/nvinput /dev/nvoutput
sudo /usr/sbin/nvhwkey-app [options] > /dev/null 2>/dev/nvinput


Then run rngd as you normally would, specifying a hwrng file as follows:
rngd [other options] -r /dev/nvoutput

**Comment by rgov** [comment]
Ok thanks, didn't realize you could use a fifo instead of a character device.

> Whats the request here?

To add a new entropy source either specifically for the `nvhwkey-app` or for executing a configurable subprocess.

> I'm not inclined to support a non open tool

The `hwkey-app` and `hwkey-agent` are both open source under MIT, I think, though at some level they're making calls into opaque hardware (as with many devices). Not sure exactly where the official repos live but as evidence [here's the LICENSE file someone uploaded](https://github.com/ESWIN-DC/Linux_for_Tegra-source/blob/c3de16d4996bc35bf8b5a5eca1dcdabdb9ba7559/trusty/app/nvidia-sample/hwkey-agent/LICENSE).

**Comment by nhorman** [comment]
Even if it is open source, which I can't confirm with your above link (a license for a related program doesn't mean the program in question is foss).  Regardless however, using this device doesn't require any extra work, you can just send stderr from that program through a fifo, and it should all "just work"
