### ISSUE TITLE
Consider a new release for compatibility with jitterentropy-3.4

### ISSUE THREAD

**Issue by thesamesam** [nhorman/rng-tools#188]
Hi folks,

Would it be possible to have a new rng-tools release including https://github.com/nhorman/rng-tools/commit/57be6d4c90e78ea9ad036a3a6e9b09822ed4d219 for compatibility with jitterentropy-3.4?

Noticed downstream in https://bugs.gentoo.org/872536.

Thanks!

**Comment by nhorman** [comment]
ACK, done:
https://github.com/nhorman/rng-tools/tree/v6.16
