### ISSUE TITLE
Is it possible to add an option to capture the random data from the source to a file rather than adding it to the kernel entropy pool ?

### ISSUE THREAD

**Issue by shankru5** [nhorman/rng-tools#192]
Hi, 

Currently, I dont see an option to capture the raw data from the entropy source into a file rather than adding it to the kernel entropy pool.

For example, I would like to directly capture the output from jitter entropy source to a file rather than feed it to the kernel entropy pool.

Is it possible to provide an option for this ? In case it already exists in some way, please let me know how to do the same.

**Comment by nhorman** [comment]
the -o option works for that

**Comment by shankru5** [comment]
Thank you ! I had earlier tried -o option before posting the question. It did not work at that time due to a silly mistake of having not created the file. The tool seems to expect that the file is already created rather than creating it if it is not there.
After I created a file and gave -o option, it worked fine. 
Thanks for the response and sorry for the oversight on my part.
