### ISSUE TITLE
Socket interface for hardware TRNGs

### ISSUE THREAD

**Issue by g-v-egidy** [nhorman/rng-tools#197]
Consider you have a hardware TRNG (for example based on zener noise, radio noise or similar) and want to feed it's data into the kernel. Then you need some hardware specific code that reads in the random data for example over serial or usb, maybe postprocesses and checks it, and then feeds it into the kernel. You probably want to mix this data with the other random sources available to rngd. For the latter I think you'd need an interface into rngd.

I think it would be best not to clutter rngd with drivers for many different hardware rngs. Because it limits the way the drivers can be written and makes it more complicated to distribute new drivers. Think programming languages, build system, dependencies, long-term-stable distributions having old versions of rngd, license.

How about offering a easy to use interface for this instead? I'm thinking about using a unix socket:
- rngd would get a "socket" driver
- parameters for it would be the path, file access mode, user, group.
- rngd creates the socket and waits for the external driver to push data into it
- the socket would be blocking: rngd only reads data from the socket when it needs new data. The hardware specific driver would push data into it until the socket blocks. 
- there wouldn't be a special protocol used for this, raw random bytes are written to the socket. rngd mixes them with the other random sources and fills them into the kernel entropy pool
- would also allow the hardware rng to be somewhere remote. Then something like socat could be used to forward the entropy over a secured network channel.

I think the alternative would be to completely leave rngd out of the picture and directly fill data from the hardware rng driver into the kernel entropy pool. rngd would do the same and the entropy from both is mixed by the kernel. When using a modern kernel and the `--force-reseed=nnn` option, the hardware rng driver and rngd both would do a force reseed every nnn seconds.

Does the socket driver idea make sense to you?

Which alternative do you think is the better approach, especially in the light of new kernels without entropy fill watermark?

**Comment by nhorman** [comment]
What you are describing is the purpose of rngd.  Its interface to the kernel is the ioctl interface of /dev/random (or whatever character device you have that leads to the random pool).  The kernel takes any entropy received from that interface and mixes it with existing entropy.

rngds purpose is to gather that new entropy from various sources, for which there are rngd drivers (or entropy soruces in rngd parlance)

This is done purposefully for two reasons:
1) Adding new kernel drivers to collect entropy is significatnly more effort than adding collection code to a user space application
2) The selection of which entropy sources to draw from is generally considered an administrative decision rather than kernel based policy

I'm not sure I see what advantage there is in your proposal.  If you want to add an entropy source that isn't currently covered by rngd, you can specify the -r option (defaults to /dev/hwrng), but can be any character device.  rngd will read from it as needed, and you can create the device you specify as a pipe/fifo to which some other application feeds data into it.

**Comment by g-v-egidy** [comment]
> I'm not sure I see what advantage there is in your proposal. If you want to add an entropy source that isn't currently covered by rngd, you can specify the -r option (defaults to /dev/hwrng), but can be any character device. rngd will read from it as needed, and you can create the device you specify as a pipe/fifo to which some other application feeds data into it.

My idea was to allow to easily add additional userspace drivers.

Yes, I can use the -r option in combination with a fifo to do this. But it means replacing the default kernel hwrng driver from /dev/hwrng with something else, I can't use it additionally to the my other userspace driver.

In cases where I really need the networking, I could use something like socat to translate between a socket and the fifo/pipe.

So the minimal approach would be to allow using a second pipe in addition to /dev/hwrng.

**Comment by nhorman** [comment]
Well, you have a few options there:
1) You can create another entropy source to be built into rngd directly, which I would gladly consider, that reads entropy from any general character device, so you had a named source that you could use to specify an arbitrary device to read from (see the entropy_sources array for how to do this)

2) You can create a process that iteratively reads from both /dev/hwrng, and whatever other source you want, mixes them in whatever way you like, and feeds that into the named pipe as specified by the rngd -r option

**Comment by g-v-egidy** [comment]
Which of these do you think is architecturally the better one?

On first glance it looks to me like option 1 is the better one. Because then rngd knows that /dev/hwrng and my custom source are two distinct things, can do health checking separately and so on. With option 2 this would have to be reimplemented in my mixing process.

Option 2 has the benefit that it would allow me to control the mixing strategy in more detail than rngd offers right now. But as long as one source doesn't completely dominate over the others I'm not really concerned about this.

**Comment by nhorman** [comment]
I think thats entirely up to you.  Option 1 is likely more in line the current architecture of rng-tools, as every entropy source is written as a set of function pointers and data.

But option two is perfectly reasonable as well, and requires no rng-tools code changes.

I would say start with option 2, as you can likely implement it as a shell script, and once you have it working, if you find it really useful, take the extra hour and write it up as a PR for rng-tools proper.
