### ISSUE TITLE
rng-tools-6.3 not working with odroid C1+ on Funtoo

### ISSUE THREAD

**Issue by yuyuyak** [nhorman/rng-tools#20]
Hi.  Funtoo upgraded from rng-tools-6.2 which works fine to rng-tools-6.3 which works not at all.  Trying to start from openrc I get:
`
\# /etc/init.d/rngd start
 * Caching service dependencies ...                                                                                    [ ok ]
 * Starting rngd ...
Failed to init entropy source 0: Hardware RNG Device

Failed to init entropy source 1: TPM RNG Device

can't open any entropy source
Maybe RNG device modules are not loaded

 * start-stop-daemon: failed to start `/usr/sbin/rngd'
 * Failed to start rngd                                                                                                [ !! ]
 * ERROR: rngd failed to start
`

I tried command line:
`
\# rngd -r /dev/hwrng -x 1 -n 0 -f
Disabling 1: TPM RNG Device
Enabling 0: Hardware RNG Device

Initalizing available sources
I is 1
I is 2
I is 3
I is 4
I is 5
...
I is 1
I is 2
I is 3
I is 4
I is 5
No entropy sources working, exiting rngd
`
Compared with rng-tools-6.2:
`
\# rngd -r /dev/hwrng -x 1 -n 0 -f
Disabling 1: TPM RNG Device
Enabling 0: Hardware RNG Device
<keeps on tickin'...>
`
And openrc:
`
\# /etc/init.d/rngd start
 * Caching service dependencies ...                                                                                    [ ok ]
 * Starting rngd ...
Disabling 1: TPM RNG Device                                                                                            [ ok ]
`
I am happy to assist with testing.  Thank you and especially thank you for rng-tools!

**Comment by yuyuyak** [comment]
Tested, works like a charm.  Thank you.

**Comment by nhorman** [comment]
Roger, will push a new release shortly
