### ISSUE TITLE
Coarse mixing of multiple entropy sources

### ISSUE THREAD

**Issue by g-v-egidy** [nhorman/rng-tools#201]
when rngd currently has multiple entropy sources available, the way they are used is like this (pseudocode):
```
FIPS_RNG_BUFFER_SIZE=2500
random_step=64

for src in sources:
   entropy = read_from_source(src, FIPS_RNG_BUFFER_SIZE)
   if (fips_test_ok(entropy)):
      for(p=0; p<FIPS_RNG_BUFFER_SIZE; p+=FIPS_RNG_BUFFER_SIZE):
          feed_entropy_to_kernel(entropy[p], random_step)
```

A large chunk of bytes is read from a source, tested, and then fed in by default 39 steps to the kernel until finished. Only then the next entropy source is considered. When considering a modern kernel without observable fill watermark (>= 5.18), and using --force-reseed with the default option of 5 minutes, this means entropy from one source is fed to the kernel over the course of 195 minutes before the next source is used. This leads to quite a coarse mixing of different entropy sources.

It is my understanding that mixing entropy from different sources at least helps should one of the sources be not as random as expected.

The coarse way the mixing is done right now doesn't really facilitate this.

I suggest to change the way the mixing is done to something like this:
- first get a block with FIPS_RNG_BUFFER_SIZE of entropy from each enabled source
- check the blocks, only take the ones that pass the fips test
- loop over the blocks we got, taking one byte from each and feed the result to the kernel

This will lead to a byte-wise mixing of the different entropy sources.

Does this make sense?

**Comment by nhorman** [comment]
Seems reasonable, would you like to write a patch?

**Comment by g-v-egidy** [comment]
> would you like to write a patch?

yes, I can put developing it on my todo. But it will probably take a few days until I get to it.

Could you take a look at my open pull requests meanwhile?

**Comment by nhorman** [comment]
ack, mered/notes made
