### ISSUE TITLE
security code scanner reports an issue at rngd_jitter.c:329

### ISSUE THREAD

**Issue by nefigtut** [nhorman/rng-tools#209]
hi, a security code scanner reports a security issue at `rngd_jitter.c:329`. i would rate this issue as Low, but probably it is worth fixing. The scanner reports:

```
Error: INTEGER_OVERFLOW (CWE-190):
rng-tools-6.16/rngd_jitter.c:329:4: tainted_data_return: Called function "write(me->pipe_fd, &tmpbuf[written], me->buf_sz - written)", and a possible return value may be less than zero.
rng-tools-6.16/rngd_jitter.c:329:4: assign: Assigning: "ret" = "write(me->pipe_fd, &tmpbuf[written], me->buf_sz - written)".
rng-tools-6.16/rngd_jitter.c:333:4: overflow: The expression "written" is considered to have possibly overflowed.
rng-tools-6.16/rngd_jitter.c:329:4: overflow: The expression "me->buf_sz - written" is deemed overflowed because at least one of its arguments has overflowed.
rng-tools-6.16/rngd_jitter.c:329:4: overflow_sink: "me->buf_sz - written", which might have underflowed, is passed to "write(me->pipe_fd, &tmpbuf[written], me->buf_sz - written)".

#  326|                 written = 0;
#  327|   		while(written != me->buf_sz) {
#  328|   			message_entsrc(me->ent_src,LOG_DAEMON|LOG_DEBUG, "Writing to pipe\n");
#  329|-> 			ret = write(me->pipe_fd, &tmpbuf[written], me->buf_sz - written);
#  330|                         if ((ret < 0) && (errno != EBADF))
#  331|   				message_entsrc(me->ent_src,LOG_DAEMON|LOG_WARNING, "Error on pipe write: %s\n", strerror(errno));
#  332|                         message_entsrc(me->ent_src,LOG_DAEMON|LOG_DEBUG, "DONE Writing to pipe with return %ld\n", ret);
#  333|                         written += ret;
```

a case of negative `ret` is checked, but only a warning is logged, no error-handling actions are taken. then a negative `ret` is added to `written` which breaks the `while()` loop logic. this may end up as an infinite loop.

unfortunately, i don't quite get the code logic here and do not understand how to handle a `write()` error and exit properly.

or is it enough to put `written += ret` in the else branch? but then an infinite loop is still possible.

**Comment by nhorman** [comment]
My guess is that the most direct solution would be to avoid updating written, if ret returns a negative value, bailing out after some number of errors in the loop.  Something like this (untested):

```
diff --git a/rngd_jitter.c b/rngd_jitter.c
index 3ff15e1..91b93d4 100644
--- a/rngd_jitter.c
+++ b/rngd_jitter.c
@@ -265,6 +265,7 @@ static void *thread_entropy_task(void *data)
        char *tmpbuf;
        struct timespec start, end;
        int written;
+    int maxerr = 3;
        /* STARTUP */
 
        sigemptyset(&blockset);
@@ -327,10 +328,16 @@ static void *thread_entropy_task(void *data)
                while(written != me->buf_sz) {
                        message_entsrc(me->ent_src,LOG_DAEMON|LOG_DEBUG, "Writing to pipe\n");
                        ret = write(me->pipe_fd, &tmpbuf[written], me->buf_sz - written);
-                        if ((ret < 0) && (errno != EBADF))
+            if ((ret < 0) && (errno != EBADF)) {
                                message_entsrc(me->ent_src,LOG_DAEMON|LOG_WARNING, "Error on pipe write: %s\n", strerror(errno));
-                       message_entsrc(me->ent_src,LOG_DAEMON|LOG_DEBUG, "DONE Writing to pipe with return %ld\n", ret);
-                       written += ret;
+                if (maxerr-- == 0) {
+                    message_entsrc(me->ent_src, LOG_DAEMON|LOG_ERR, "Too many pipe errors, bailing out\n");
+                    goto out_interrupt;
+                }
+            } else {
+                message_entsrc(me->ent_src,LOG_DAEMON|LOG_DEBUG, "DONE Writing to pipe with return %ld\n", ret);
+                written += ret;
+            }
                }
 
        }
```

Can you give that a test and see if it addresses your analyzers concerns?

**Comment by nefigtut** [comment]
hmm... what i see is a special case with EBADF. i'm not sure why EBADF is special here. anyway, if errno == EBADF, ret still can be < 0 and written += ret breaks and the loop goes mad. again, i do not uderstand this pipe code well, but i guess, EBADF case also should be handled. wdyt?

**Comment by nefigtut** [comment]
write(2) says: "EBADF - fd is not a valid file descriptor or is not open for writing". this means any future write would fail. shouldn't we bail out immediately (i.e. `goto out_interrupt;`) in this case?

**Comment by nhorman** [comment]
We certainly could, but that check was added in commit 3e47faae108df4824531bf9c003cc1c65b7b2842, which caught an error on exit (i.e. if a thread was attempting to write the pipe, while we were exiting, to prevent an ungraceful shutdown.

We could exit immediately, but its probably worth experimenting with that in a separate PR to make sure we don't re-introduce that problem.

**Comment by nefigtut** [comment]
hi, please, see #212 as a suggested fix. i've taken more steps and added error handing to the jitter read part and enhanced the write part. the error handling logic is complex now, so can you please have a closer look?

some details and explanations. please note, i may misunderstand the code and so i might have made wrong adjustments.

1) Add a counter for a maximum number of errors. If it is reached, bail out. Reset the counter on successful read or write. This will allow us to ignore a single error and continue.

2) Add error handling to the jitter read loop. Restart a read on error, since there is nothing to write out. Reset the counter on successful read.

3) Add error handling to the pipe write loop. Handle a special case of EBADF error, see 3e47faa for details.
(this desicion may be wrong, please review) In case (unlikely) ret == 0 or errno == EBADF just do nothing, restart the loop.

happy to get to know your concerns/suggestions.
