### ISSUE TITLE
rngd[xxx]: [namedpipe]: Initialization Failed

### ISSUE THREAD

**Issue by toralf** [nhorman/rng-tools#220]
From time to time I do get
```
# zgrep -h "rngd.*namedpipe" /var/log/messages* | sort -n -k 2
Oct  6 17:41:27 p14s rngd[3622]: [namedpipe]: Initialization Failed
Oct 12 15:50:52 p14s rngd[3622]: [namedpipe]: Initialization Failed
Oct 14 17:05:12 p14s rngd[12370]: [namedpipe]: Initialization Failed
Oct 14 17:06:25 p14s rngd[3622]: [namedpipe]: Initialization Failed
```
at my hardened Gentoo Linux and do wonder whether to care about it or not?

**Comment by nhorman** [comment]
If you don't intend to use the namedpipe source, then you can likely ignore it (and should likely just disable the source entirely).  Otherwise, run with --debug to see why it failed

**Comment by toralf** [comment]
ah, ok, so I'll ignore it for now.
