### ISSUE TITLE
RDSEED does not retry on failure

### ISSUE THREAD

**Issue by joshuaehill** [nhorman/rng-tools#51]
RDSEED does produce entropy, and it is reasonable to credit it at full (or nearly full) entropy.

In the code that reads from RDSEED ("x86_rdseed_or_rdrand_bytes"), after RDSEED is called, if the carry bit is not set then the code falls back to RDRAND.

As I pointed out in issue #50 RDRAND isn't a reasonable source for entropy (though it is a reasonable source for computational resistance to attack with a security strength of 128 bits). It would be useful to retry the RDSEED operation, as suggested in section 5.3.1.1. and 5.3.1.2 of [Intel's DRNG Implementation Guide](https://software.intel.com/en-us/articles/intel-digital-random-number-generator-drng-software-implementation-guide).

I suggest retrying up to 100 times, and then falling back to RDRAND. In all cases, data from RDRAND should not be credited as containing full entropy.

**Comment by nhorman** [comment]
No, as noted before rngd isn't trying to be mathematically perfect in the computation of random numbers, but rather attempting to quickly generate random data that is sufficiently non-deterministic in its output for average users purposes who want their systems to boot and operate quickly with a minimum of blockage on random data availability.  RDSEED is orders of magnitude slower than RDRAND, and if a call to RDSEED fails, executing repeatedly in a tight loop in some assembly code isn't likely to produce different results (CF=0 on a call to RDSEED will likely imply that the next call will also fail if called in close succession).  Thats why we ignore it as we do now 

Its also important to note that on a request for entropy from the rdrand source in rngd, we break a request for data up into chunks, and make multiple calls to x86_rdseed_or_rdrand_bytes, implying iterative calls to rdseed in that manner.

That said, I'd be happy to review a patch from you that allows for stricter adherence to the intel guidelines, but such an option must be opt in, as no practical user will be able to make use of an entropy source that can't keep up with a systems random data demands. 

For users that have strict security issues, and require strict random data strength, the suggestion is that they obtain separate rng hardware and have rngd draw from that via the HWRNG entropy source.
