### ISSUE TITLE
6.7: compile time warnings

### ISSUE THREAD

**Issue by kloczek** [nhorman/rng-tools#57]
It does not look good :)

<pre>rngd_linux.c: In function &apos;default_watermark&apos;:
rngd_linux.c:64:9: warning: unused variable &apos;l&apos; [-Wunused-variable]
   64 |  size_t l;
      |         ^
rngd_linux.c:62:16: warning: unused variable &apos;ps&apos; [-Wunused-variable]
   62 |  unsigned long ps;
      |                ^~
rngd_linux.c:61:19: warning: unused variable &apos;p&apos; [-Wunused-variable]
   61 |  char psbuf[64], *p;
      |                   ^
rngd_linux.c:61:7: warning: unused variable &apos;psbuf&apos; [-Wunused-variable]
   61 |  char psbuf[64], *p;
      |       ^~~~~
rngd_linux.c:70:2: warning: ignoring return value of &apos;fscanf&apos;, declared with attribute warn_unused_result [-Wunused-result]
   70 |  fscanf(f,&quot;%d&quot;, &amp;wm);
      |  ^~~~~~~~~~~~~~~~~~~
rngd_linux.c: In function &apos;random_add_entropy&apos;:
rngd_linux.c:150:3: warning: ignoring return value of &apos;write&apos;, declared with attribute warn_unused_result [-Wunused-result]
  150 |   write(random_fd, buf, size);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from rngd.c:53:
rngd.c: In function &apos;find_ent_src_idx&apos;:
rngd.c:361:31: warning: format &apos;%lu&apos; expects argument of type &apos;long unsigned int&apos;, but argument 3 has type &apos;int&apos; [-Wformat=]
  361 |    message(LOG_CONS|LOG_INFO, &quot;option index out of range: %lu\n&quot;, idx);
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~
      |                                                                   |
      |                                                                   int
rngd.h:149:22: note: in definition of macro &apos;message&apos;
  149 |   syslog((priority), fmt, ##args); \
      |                      ^~~
rngd.c:361:61: note: format string is defined here
  361 |    message(LOG_CONS|LOG_INFO, &quot;option index out of range: %lu\n&quot;, idx);
      |                                                           ~~^
      |                                                             |
      |                                                             long unsigned int
      |                                                           %u
In file included from rngd.c:53:
rngd.c:361:31: warning: format &apos;%lu&apos; expects argument of type &apos;long unsigned int&apos;, but argument 3 has type &apos;int&apos; [-Wformat=]
  361 |    message(LOG_CONS|LOG_INFO, &quot;option index out of range: %lu\n&quot;, idx);
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~
      |                                                                   |
      |                                                                   int
rngd.h:152:20: note: in definition of macro &apos;message&apos;
  152 |    fprintf(stderr, fmt, ##args); \
      |                    ^~~
rngd.c:361:61: note: format string is defined here
  361 |    message(LOG_CONS|LOG_INFO, &quot;option index out of range: %lu\n&quot;, idx);
      |                                                           ~~^
      |                                                             |
      |                                                             long unsigned int
      |                                                           %u
In file included from rngd.c:53:
rngd.c: In function &apos;parse_opt&apos;:
rngd.c:452:30: warning: format &apos;%d&apos; expects argument of type &apos;int&apos;, but argument 4 has type &apos;long int&apos; [-Wformat=]
  452 |   message(LOG_CONS|LOG_INFO, &quot;Option %s not found for source idx %d\n&quot;, optkey, idx);
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~          ~~~
      |                                                                                 |
      |                                                                                 long int
rngd.h:149:22: note: in definition of macro &apos;message&apos;
  149 |   syslog((priority), fmt, ##args); \
      |                      ^~~
rngd.c:452:67: note: format string is defined here
  452 |   message(LOG_CONS|LOG_INFO, &quot;Option %s not found for source idx %d\n&quot;, optkey, idx);
      |                                                                  ~^
      |                                                                   |
      |                                                                   int
      |                                                                  %ld
In file included from rngd.c:53:
rngd.c:452:30: warning: format &apos;%d&apos; expects argument of type &apos;int&apos;, but argument 4 has type &apos;long int&apos; [-Wformat=]
  452 |   message(LOG_CONS|LOG_INFO, &quot;Option %s not found for source idx %d\n&quot;, optkey, idx);
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~          ~~~
      |                                                                                 |
      |                                                                                 long int
rngd.h:152:20: note: in definition of macro &apos;message&apos;
  152 |    fprintf(stderr, fmt, ##args); \
      |                    ^~~
rngd.c:452:67: note: format string is defined here
  452 |   message(LOG_CONS|LOG_INFO, &quot;Option %s not found for source idx %d\n&quot;, optkey, idx);
      |                                                                  ~^
      |                                                                   |
      |                                                                   int
      |                                                                  %ld
In file included from rngd.c:53:
rngd.c: In function &apos;main&apos;:
rngd.c:831:31: warning: format &apos;%d&apos; expects argument of type &apos;int&apos;, but argument 4 has type &apos;long unsigned int&apos; [-Wformat=]
  831 |    message(LOG_CONS|LOG_INFO, &quot;\nEntropy rate: %6.4g Mbits/sec averaged over %d iterations for %6.4g seconds\n&quot;,
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  832 |     (sum_entropy/test_time/MEGABITS), test_iterations, test_time);
      |                                       ~~~~~~~~~~~~~~~
      |                                       |
      |                                       long unsigned int
rngd.h:149:22: note: in definition of macro &apos;message&apos;
  149 |   syslog((priority), fmt, ##args); \
      |                      ^~~
rngd.c:831:79: note: format string is defined here
  831 |    message(LOG_CONS|LOG_INFO, &quot;\nEntropy rate: %6.4g Mbits/sec averaged over %d iterations for %6.4g seconds\n&quot;,
      |                                                                              ~^
      |                                                                               |
      |                                                                               int
      |                                                                              %ld
In file included from rngd.c:53:
rngd.c:831:31: warning: format &apos;%d&apos; expects argument of type &apos;int&apos;, but argument 4 has type &apos;long unsigned int&apos; [-Wformat=]
  831 |    message(LOG_CONS|LOG_INFO, &quot;\nEntropy rate: %6.4g Mbits/sec averaged over %d iterations for %6.4g seconds\n&quot;,
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  832 |     (sum_entropy/test_time/MEGABITS), test_iterations, test_time);
      |                                       ~~~~~~~~~~~~~~~
      |                                       |
      |                                       long unsigned int
rngd.h:152:20: note: in definition of macro &apos;message&apos;
  152 |    fprintf(stderr, fmt, ##args); \
      |                    ^~~
rngd.c:831:79: note: format string is defined here
  831 |    message(LOG_CONS|LOG_INFO, &quot;\nEntropy rate: %6.4g Mbits/sec averaged over %d iterations for %6.4g seconds\n&quot;,
      |                                                                              ~^
      |                                                                               |
      |                                                                               int
      |                                                                              %ld
In file included from rngd.c:53:
rngd.c:834:31: warning: format &apos;%d&apos; expects argument of type &apos;int&apos;, but argument 4 has type &apos;long unsigned int&apos; [-Wformat=]
  834 |    message(LOG_CONS|LOG_INFO, &quot;\nEntropy rate: %6.4g Kbits/sec averaged over %d iterations for %6.4g seconds\n&quot;,
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  835 |     (sum_entropy/test_time/KILOBITS), test_iterations, test_time);
      |                                       ~~~~~~~~~~~~~~~
      |                                       |
      |                                       long unsigned int
rngd.h:149:22: note: in definition of macro &apos;message&apos;
  149 |   syslog((priority), fmt, ##args); \
      |                      ^~~
rngd.c:834:79: note: format string is defined here
  834 |    message(LOG_CONS|LOG_INFO, &quot;\nEntropy rate: %6.4g Kbits/sec averaged over %d iterations for %6.4g seconds\n&quot;,
      |                                                                              ~^
      |                                                                               |
      |                                                                               int
      |                                                                              %ld
In file included from rngd.c:53:
rngd.c:834:31: warning: format &apos;%d&apos; expects argument of type &apos;int&apos;, but argument 4 has type &apos;long unsigned int&apos; [-Wformat=]
  834 |    message(LOG_CONS|LOG_INFO, &quot;\nEntropy rate: %6.4g Kbits/sec averaged over %d iterations for %6.4g seconds\n&quot;,
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  835 |     (sum_entropy/test_time/KILOBITS), test_iterations, test_time);
      |                                       ~~~~~~~~~~~~~~~
      |                                       |
      |                                       long unsigned int
rngd.h:152:20: note: in definition of macro &apos;message&apos;
  152 |    fprintf(stderr, fmt, ##args); \
      |                    ^~~
rngd.c:834:79: note: format string is defined here
  834 |    message(LOG_CONS|LOG_INFO, &quot;\nEntropy rate: %6.4g Kbits/sec averaged over %d iterations for %6.4g seconds\n&quot;,
      |                                                                              ~^
      |                                                                               |
      |                                                                               int
      |                                                                              %ld
At top level:
rngd.c:156:3: warning: &apos;entropy_indexes&apos; defined but not used [-Wunused-variable]
  156 | } entropy_indexes;
      |   ^~~~~~~~~~~~~~~
rngd_rdrand.c: In function &apos;init_drng_entropy_source&apos;:
rngd_rdrand.c:356:3: warning: ignoring return value of &apos;read&apos;, declared with attribute warn_unused_result [-Wunused-result]
  356 |   read(fd, key, sizeof key);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from rngd_jitter.c:36:
rngd_jitter.c: In function &apos;xread_jitter&apos;:
rngd_jitter.c:156:33: warning: format &apos;%d&apos; expects argument of type &apos;int&apos;, but argument 3 has type &apos;ssize_t&apos; {aka &apos;long int&apos;} [-Wformat=]
  156 |   message(LOG_DAEMON|LOG_DEBUG, &quot;xread_jitter requests %d bytes from pipe\n&quot;, need);
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~
      |                                                                               |
      |                                                                               ssize_t {aka long int}
rngd.h:149:22: note: in definition of macro &apos;message&apos;
  149 |   syslog((priority), fmt, ##args); \
      |                      ^~~
rngd_jitter.c:156:57: note: format string is defined here
  156 |   message(LOG_DAEMON|LOG_DEBUG, &quot;xread_jitter requests %d bytes from pipe\n&quot;, need);
      |                                                        ~^
      |                                                         |
      |                                                         int
      |                                                        %ld
In file included from rngd_jitter.c:36:
rngd_jitter.c:156:33: warning: format &apos;%d&apos; expects argument of type &apos;int&apos;, but argument 3 has type &apos;ssize_t&apos; {aka &apos;long int&apos;} [-Wformat=]
  156 |   message(LOG_DAEMON|LOG_DEBUG, &quot;xread_jitter requests %d bytes from pipe\n&quot;, need);
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~
      |                                                                               |
      |                                                                               ssize_t {aka long int}
rngd.h:152:20: note: in definition of macro &apos;message&apos;
  152 |    fprintf(stderr, fmt, ##args); \
      |                    ^~~
rngd_jitter.c:156:57: note: format string is defined here
  156 |   message(LOG_DAEMON|LOG_DEBUG, &quot;xread_jitter requests %d bytes from pipe\n&quot;, need);
      |                                                        ~^
      |                                                         |
      |                                                         int
      |                                                        %ld
rngd_jitter.c:165:19: warning: pointer targets in passing argument 1 of &apos;gcrypt_mangle&apos; differ in signedness [-Wpointer-sign]
  165 |     gcrypt_mangle(aes_buf, current-&gt;buf_sz);
      |                   ^~~~~~~
      |                   |
      |                   char *
rngd_jitter.c:115:48: note: expected &apos;unsigned char *&apos; but argument is of type &apos;char *&apos;
  115 | static inline int gcrypt_mangle(unsigned char *tmp, size_t size)
      |                                 ~~~~~~~~~~~~~~~^~~
In file included from rngd_jitter.c:36:
rngd_jitter.c:176:35: warning: format &apos;%d&apos; expects argument of type &apos;int&apos;, but argument 3 has type &apos;ssize_t&apos; {aka &apos;long int&apos;} [-Wformat=]
  176 |     message(LOG_DAEMON|LOG_DEBUG, &quot;request of random data returns %d less than need %d\n&quot;,
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  177 |      request, need);
      |      ~~~~~~~                       
      |      |
      |      ssize_t {aka long int}
rngd.h:149:22: note: in definition of macro &apos;message&apos;
  149 |   syslog((priority), fmt, ##args); \
      |                      ^~~
rngd_jitter.c:176:68: note: format string is defined here
  176 |     message(LOG_DAEMON|LOG_DEBUG, &quot;request of random data returns %d less than need %d\n&quot;,
      |                                                                   ~^
      |                                                                    |
      |                                                                    int
      |                                                                   %ld
In file included from rngd_jitter.c:36:
rngd_jitter.c:176:35: warning: format &apos;%d&apos; expects argument of type &apos;int&apos;, but argument 4 has type &apos;ssize_t&apos; {aka &apos;long int&apos;} [-Wformat=]
  176 |     message(LOG_DAEMON|LOG_DEBUG, &quot;request of random data returns %d less than need %d\n&quot;,
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  177 |      request, need);
      |               ~~~~                 
      |               |
      |               ssize_t {aka long int}
rngd.h:149:22: note: in definition of macro &apos;message&apos;
  149 |   syslog((priority), fmt, ##args); \
      |                      ^~~
rngd_jitter.c:176:86: note: format string is defined here
  176 |     message(LOG_DAEMON|LOG_DEBUG, &quot;request of random data returns %d less than need %d\n&quot;,
      |                                                                                     ~^
      |                                                                                      |
      |                                                                                      int
      |                                                                                     %ld
In file included from rngd_jitter.c:36:
rngd_jitter.c:176:35: warning: format &apos;%d&apos; expects argument of type &apos;int&apos;, but argument 3 has type &apos;ssize_t&apos; {aka &apos;long int&apos;} [-Wformat=]
  176 |     message(LOG_DAEMON|LOG_DEBUG, &quot;request of random data returns %d less than need %d\n&quot;,
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  177 |      request, need);
      |      ~~~~~~~                       
      |      |
      |      ssize_t {aka long int}
rngd.h:152:20: note: in definition of macro &apos;message&apos;
  152 |    fprintf(stderr, fmt, ##args); \
      |                    ^~~
rngd_jitter.c:176:68: note: format string is defined here
  176 |     message(LOG_DAEMON|LOG_DEBUG, &quot;request of random data returns %d less than need %d\n&quot;,
      |                                                                   ~^
      |                                                                    |
      |                                                                    int
      |                                                                   %ld
In file included from rngd_jitter.c:36:
rngd_jitter.c:176:35: warning: format &apos;%d&apos; expects argument of type &apos;int&apos;, but argument 4 has type &apos;ssize_t&apos; {aka &apos;long int&apos;} [-Wformat=]
  176 |     message(LOG_DAEMON|LOG_DEBUG, &quot;request of random data returns %d less than need %d\n&quot;,
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  177 |      request, need);
      |               ~~~~                 
      |               |
      |               ssize_t {aka long int}
rngd.h:152:20: note: in definition of macro &apos;message&apos;
  152 |    fprintf(stderr, fmt, ##args); \
      |                    ^~~
rngd_jitter.c:176:86: note: format string is defined here
  176 |     message(LOG_DAEMON|LOG_DEBUG, &quot;request of random data returns %d less than need %d\n&quot;,
      |                                                                                     ~^
      |                                                                                      |
      |                                                                                      int
      |                                                                                     %ld
In file included from rngd_jitter.c:36:
rngd_jitter.c:188:33: warning: format &apos;%d&apos; expects argument of type &apos;int&apos;, but argument 3 has type &apos;ssize_t&apos; {aka &apos;long int&apos;} [-Wformat=]
  188 |   message(LOG_DAEMON|LOG_DEBUG, &quot;xread_jitter gets %d bytes\n&quot;, request);
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~
      |                                                                 |
      |                                                                 ssize_t {aka long int}
rngd.h:149:22: note: in definition of macro &apos;message&apos;
  149 |   syslog((priority), fmt, ##args); \
      |                      ^~~
rngd_jitter.c:188:53: note: format string is defined here
  188 |   message(LOG_DAEMON|LOG_DEBUG, &quot;xread_jitter gets %d bytes\n&quot;, request);
      |                                                    ~^
      |                                                     |
      |                                                     int
      |                                                    %ld
In file included from rngd_jitter.c:36:
rngd_jitter.c:188:33: warning: format &apos;%d&apos; expects argument of type &apos;int&apos;, but argument 3 has type &apos;ssize_t&apos; {aka &apos;long int&apos;} [-Wformat=]
  188 |   message(LOG_DAEMON|LOG_DEBUG, &quot;xread_jitter gets %d bytes\n&quot;, request);
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~
      |                                                                 |
      |                                                                 ssize_t {aka long int}
rngd.h:152:20: note: in definition of macro &apos;message&apos;
  152 |    fprintf(stderr, fmt, ##args); \
      |                    ^~~
rngd_jitter.c:188:53: note: format string is defined here
  188 |   message(LOG_DAEMON|LOG_DEBUG, &quot;xread_jitter gets %d bytes\n&quot;, request);
      |                                                    ~^
      |                                                     |
      |                                                     int
      |                                                    %ld
rngd_jitter.c:150:18: warning: unused variable &apos;sleep&apos; [-Wunused-variable]
  150 |  struct timespec sleep;
      |                  ^~~~~
In file included from rngd_jitter.c:36:
rngd_jitter.c: In function &apos;thread_entropy_task&apos;:
rngd_jitter.c:290:34: warning: format &apos;%d&apos; expects argument of type &apos;int&apos;, but argument 3 has type &apos;ssize_t&apos; {aka &apos;long int&apos;} [-Wformat=]
  290 |    message(LOG_DAEMON|LOG_DEBUG, &quot;DONE Writing to pipe with return %d\n&quot;, ret);
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~
      |                                                                           |
      |                                                                           ssize_t {aka long int}
rngd.h:149:22: note: in definition of macro &apos;message&apos;
  149 |   syslog((priority), fmt, ##args); \
      |                      ^~~
rngd_jitter.c:290:69: note: format string is defined here
  290 |    message(LOG_DAEMON|LOG_DEBUG, &quot;DONE Writing to pipe with return %d\n&quot;, ret);
      |                                                                    ~^
      |                                                                     |
      |                                                                     int
      |                                                                    %ld
In file included from rngd_jitter.c:36:
rngd_jitter.c:290:34: warning: format &apos;%d&apos; expects argument of type &apos;int&apos;, but argument 3 has type &apos;ssize_t&apos; {aka &apos;long int&apos;} [-Wformat=]
  290 |    message(LOG_DAEMON|LOG_DEBUG, &quot;DONE Writing to pipe with return %d\n&quot;, ret);
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~
      |                                                                           |
      |                                                                           ssize_t {aka long int}
rngd.h:152:20: note: in definition of macro &apos;message&apos;
  152 |    fprintf(stderr, fmt, ##args); \
      |                    ^~~
rngd_jitter.c:290:69: note: format string is defined here
  290 |    message(LOG_DAEMON|LOG_DEBUG, &quot;DONE Writing to pipe with return %d\n&quot;, ret);
      |                                                                    ~^
      |                                                                     |
      |                                                                     int
      |                                                                    %ld
rngd_jitter.c:239:9: warning: unused variable &apos;need&apos; [-Wunused-variable]
  239 |  size_t need;
      |         ^~~~
rngd_jitter.c: In function &apos;close_jitter_entropy_source&apos;:
rngd_jitter.c:489:5: warning: ignoring return value of &apos;read&apos;, declared with attribute warn_unused_result [-Wunused-result]
  489 |     read(pipefds[0], tmpbuf, 1024);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At top level:
rngd_jitter.c:75:12: warning: &apos;init_gcrypt&apos; defined but not used [-Wunused-function]
   75 | static int init_gcrypt(const void *key)
      |            ^~~~~~~~~~~
rngd_jitter.c:41:26: warning: &apos;ec&apos; defined but not used [-Wunused-variable]
   41 | static struct rand_data *ec = NULL;
      |                          ^~
In file included from rngd_nistbeacon.c:54:
rngd_nistbeacon.c: In function &apos;get_nist_record&apos;:
rngd_nistbeacon.c:417:33: warning: format &apos;%d&apos; expects argument of type &apos;int&apos;, but argument 3 has type &apos;uint64_t&apos; {aka &apos;long unsigned int&apos;} [-Wformat=]
  417 |   message(LOG_DAEMON|LOG_DEBUG, &quot;NIST: timestamp is %d, frequency is %d, tv_sec is %d\n&quot;,
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  418 |    block.timestamp, block.frequency, ct.tv_sec);
      |    ~~~~~~~~~~~~~~~               
      |         |
      |         uint64_t {aka long unsigned int}
rngd.h:149:22: note: in definition of macro &apos;message&apos;
  149 |   syslog((priority), fmt, ##args); \
      |                      ^~~
rngd_nistbeacon.c:417:54: note: format string is defined here
  417 |   message(LOG_DAEMON|LOG_DEBUG, &quot;NIST: timestamp is %d, frequency is %d, tv_sec is %d\n&quot;,
      |                                                     ~^
      |                                                      |
      |                                                      int
      |                                                     %ld
In file included from rngd_nistbeacon.c:54:
rngd_nistbeacon.c:417:33: warning: format &apos;%d&apos; expects argument of type &apos;int&apos;, but argument 5 has type &apos;__time_t&apos; {aka &apos;long int&apos;} [-Wformat=]
  417 |   message(LOG_DAEMON|LOG_DEBUG, &quot;NIST: timestamp is %d, frequency is %d, tv_sec is %d\n&quot;,
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  418 |    block.timestamp, block.frequency, ct.tv_sec);
      |                                      ~~~~~~~~~
      |                                        |
      |                                        __time_t {aka long int}
rngd.h:149:22: note: in definition of macro &apos;message&apos;
  149 |   syslog((priority), fmt, ##args); \
      |                      ^~~
rngd_nistbeacon.c:417:85: note: format string is defined here
  417 |   message(LOG_DAEMON|LOG_DEBUG, &quot;NIST: timestamp is %d, frequency is %d, tv_sec is %d\n&quot;,
      |                                                                                    ~^
      |                                                                                     |
      |                                                                                     int
      |                                                                                    %ld
In file included from rngd_nistbeacon.c:54:
rngd_nistbeacon.c:417:33: warning: format &apos;%d&apos; expects argument of type &apos;int&apos;, but argument 3 has type &apos;uint64_t&apos; {aka &apos;long unsigned int&apos;} [-Wformat=]
  417 |   message(LOG_DAEMON|LOG_DEBUG, &quot;NIST: timestamp is %d, frequency is %d, tv_sec is %d\n&quot;,
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  418 |    block.timestamp, block.frequency, ct.tv_sec);
      |    ~~~~~~~~~~~~~~~               
      |         |
      |         uint64_t {aka long unsigned int}
rngd.h:152:20: note: in definition of macro &apos;message&apos;
  152 |    fprintf(stderr, fmt, ##args); \
      |                    ^~~
rngd_nistbeacon.c:417:54: note: format string is defined here
  417 |   message(LOG_DAEMON|LOG_DEBUG, &quot;NIST: timestamp is %d, frequency is %d, tv_sec is %d\n&quot;,
      |                                                     ~^
      |                                                      |
      |                                                      int
      |                                                     %ld
In file included from rngd_nistbeacon.c:54:
rngd_nistbeacon.c:417:33: warning: format &apos;%d&apos; expects argument of type &apos;int&apos;, but argument 5 has type &apos;__time_t&apos; {aka &apos;long int&apos;} [-Wformat=]
  417 |   message(LOG_DAEMON|LOG_DEBUG, &quot;NIST: timestamp is %d, frequency is %d, tv_sec is %d\n&quot;,
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  418 |    block.timestamp, block.frequency, ct.tv_sec);
      |                                      ~~~~~~~~~
      |                                        |
      |                                        __time_t {aka long int}
rngd.h:152:20: note: in definition of macro &apos;message&apos;
  152 |    fprintf(stderr, fmt, ##args); \
      |                    ^~~
rngd_nistbeacon.c:417:85: note: format string is defined here
  417 |   message(LOG_DAEMON|LOG_DEBUG, &quot;NIST: timestamp is %d, frequency is %d, tv_sec is %d\n&quot;,
      |                                                                                    ~^
      |                                                                                     |
      |                                                                                     int
      |                                                                                    %ld
In function &apos;get_nist_record&apos;,
    inlined from &apos;refill_rand&apos; at rngd_nistbeacon.c:120:6:
rngd_nistbeacon.c:432:2: warning: call to &apos;_curl_easy_setopt_err_cb_data&apos; declared with attribute warning: curl_easy_setopt expects a private data pointer as argument for this option [-Wattribute-warning]
  432 |  curl_easy_setopt(curl, CURLOPT_WRITEDATA, nist_rand_buf);
      |  ^
</pre>

**Comment by nhorman** [comment]
Neither does opening issues that dump out warnings saying "you should fix that" :) .  I'll get to it eventually, but patches are always welcome

**Comment by nhorman** [comment]
also, what commit level are you working from?  many of these warnings already appear corrected, and the line numbers don't match up to the head of the tree

**Comment by kloczek** [comment]
It is quite possible that some of those warnings are new for you if you are not using gcc 9 :)
Those warnings are against 6.7 tag.

**Comment by nhorman** [comment]
fixed in https://github.com/nhorman/rng-tools/pull/60

**Comment by kloczek** [comment]
I think that it would be now good to make new release :)
