### ISSUE TITLE
Dynamically determine location of opensc library

### ISSUE THREAD

**Issue by JohnAZoidberg** [nhorman/rng-tools#58]
Here https://github.com/nhorman/rng-tools/blob/master/rngd.c#L218 the path to the opensc is hardcoded. It would be great if it would find it either automatically or be overridable with the `./configure` script.

We have to patch it when packaging for a distribution where the libraries are in a different place: https://github.com/NixOS/nixpkgs/pull/60247

**Comment by nhorman** [comment]
yeah, that would be great.  Unfortunately, the only way to do that is to fish about in the file system looking for a library matching a name, and I'm not keen on the idea of loading a library that the user doesn't always expect to be loaded.

FWIW, you don't have to patch it at build time, its overrideable at runtime with the -O option.  You can simply code that into whatever startup file you use (a systemd unit file or sysv init file, etc).
