### ISSUE TITLE
gentoo patches 6.7

### ISSUE THREAD

**Issue by nicola-lunghi** [nhorman/rng-tools#65]
Hi
I just saw those patches on the gentoo recipe

https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-apps/rng-tools/rng-tools-6.7.ebuild
https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-apps/rng-tools/files/test-for-argp.patch
https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-apps/rng-tools/files/rng-tools-5-fix-textrels-on-PIC-x86.patch

https://bugs.gentoo.org/469962

can you check if they apply?

Thanks
Nick
Thanks

**Comment by nhorman** [comment]
The ebuild file isn't a patch, its the gentoo build script

The argp test isn't valuable, I can't think of a glibc build that doesn't contain argp processing

the PIC patch, maybe, I guess.  If you want to open a pull request, I can look at it more closely

**Comment by nicola-lunghi** [comment]
- The argp test isn't valuable, I can't think of a glibc build that doesn't contain argp processing
is needed with musl
for example:
  https://github.com/openwrt/packages/pull/1397
gentoo:
  elibc_musl? ( sys-libs/argp-standalone )
yocto:
  http://cgit.openembedded.org/openembedded-core/tree/meta/recipes-support/rng-tools/rng-tools_6.6.bb?h=master#n6

**Comment by nhorman** [comment]
ok, if you want to open a pull request for it, I can look into it
