### ISSUE TITLE
Add stripped down OpenSSL wait_random_seeded() ?

### ISSUE THREAD

**Issue by abelbeck** [nhorman/rng-tools#71]
@nhorman : Starting with OpenSSL 1.1.1d, a new function `wait_random_seeded()` was added that uses shared memory calls (ex. `shmget`) to note when a check for /dev/random is readable.

https://github.com/openssl/openssl/blob/OpenSSL_1_1_1d/crypto/rand/rand_unix.c#L373

This causes a problem with sandboxes with syscall whitelists, without tweaking the whitelists.

This OpenSSL 1.1.1d check can be disabled by compiling it with
```
-DOPENSSL_RAND_SEED_DEVRANDOM_SHM_ID=-1
```
So this is where `rng-tools` comes in ...

Would it make sense for `rng-tools` to perform the same basic check at start (before forking):
```
            /* Open /dev/random and wait for it to be readable */
            if ((fd = open(DEVRANDOM_WAIT, O_RDONLY)) != -1) {
                if (DEVRANDM_WAIT_USE_SELECT && fd < FD_SETSIZE) {
                    FD_ZERO(&fds);
                    FD_SET(fd, &fds);
                    while ((r = select(fd + 1, &fds, NULL, NULL, NULL)) < 0
                           && errno == EINTR);
                } else {
                    while ((r = read(fd, &c, 1)) < 0 && errno == EINTR);
                }
                close(fd);
            }
```
so distros could safely disable the check in OpenSSL ?

Presumably `rngd` is called before OpenSSL's libcrypto.

Thoughts ?

**Comment by abelbeck** [comment]
I gave this a try, and it worked perfectly on bare metal, but for one particular low-entropy VM the `select` blocked forever.  Though OpenSSL somehow works with `shmget` creating shm key `114`.

Closing.

**Comment by abelbeck** [comment]
@nhorman : Followup, for the record ...

Tested this idea for a particular VM guest which booted with a `/proc/sys/kernel/random/entropy_avail` value of `0`.  So when calling `select(2)` on `/dev/random` at the beginning of `rngd` it blocks forever and does not allow any entropy to be added.  Not good.

So, this idea may still have merit, but must be implemented after `rngd` has added entropy and/or `/proc/sys/kernel/random/entropy_avail` is an acceptable value.

Possibly a new, almost trivial, `rng-wait` application that sleeps up to 10 seconds (configurable) waiting for `/proc/sys/kernel/random/entropy_avail` to be at least `256` (configurable) and then tests (aka OpenSSL) whether `/dev/random` is readable for kernels < 4.8 or calls `getrandom(2)` for kernels >= 4.8.

Typical usage, after `rngd` is called in the background,
```
rng-wait -t 10 -e 256
```
would wait and sleep (`rngd` doing its thing) until the system had acceptable entropy to continue starting services.

**Comment by nhorman** [comment]
I'm not sure what purpose this  check serves in rngd, and truthfully,  I'm not sure what advantage it offers in openssl, nor am I confident that this is ever safe to do in rngd. 

I get using select to see if /dev/random will block, but select is never a guarantee that the system will have entropy.  Saying an entropy pool is seeded, just means its seeded at this instant in time, so a select call or shared memory segment indicating entropy availability isn't any sort of guaranteed signal to other processes that it will be available when they needed.  Other processes may as well just read /proc/sys/kernel/entropy_avail directly.

And if DEVRANDOM_WAIT_USE_SELECT isn't defined, you have a real deadlock problem.  Even if rngd seeds some entropy before making this check, theres nothing guaranteing some other process didn't drain it right away, meaning that read of /dev/random will block for lack of entropy, and that will prevent rngd from creating more entropy to satisfy the request.

**Comment by abelbeck** [comment]
@nhorman : Thanks for commenting.

Just curious, for OpenSSL, could just the `/proc/sys/kernel/random/entropy_avail` value be used instead of `select(2)` readability of /dev/random in their `wait_random_seeded()` check ?  That would be non-blocking and could be evaluated anytime `libcrypto` is loaded, and would not require any shared memory marker.

**Comment by nhorman** [comment]
Sure, it certainly could, but  doing so would be linux specific, whereas the method they currently use is POSIX compliant and works on all the OS environments that OpenSSL supports.  And doing so doesn't really solve the desired problem, which is that callers of wait_random_seeded want to know if /dev/random is likely to not block when called.  No matter what you do, even if wait_random_seeded says that yes, its been seeded, that in no way guarantees that /dev/random won't block at some arbitrary point in the future.

What might be a better a better solution, would be to have some way to determine if there is a process that has opened /dev/random and written to it.  Such a test would suggest to callers that there is a process that is filling the entropy pool (like rngd), so that any calls to read /dev/random, if they block, are likely to unblock in a short period of time, as the writing process will refill the pool
