### ISSUE TITLE
Improve reporting of entropy source initialization

### ISSUE THREAD

**Issue by JohnAZoidberg** [nhorman/rng-tools#75]
When I start rngd I get this output:
```
$ sudo rngd -f
Initializing available sources      
                                    
Initializing entropy source hwrng   
                                    
Enabling RDSEED rng support         
                                    
Initializing entropy source rdrand  
                                    
Initializing AES buffer             
                                    
Enabling JITTER rng support         
                                    
Initializing entropy source jitter  
                                    
No pkcs11 slots available           
                                    
Failed to init entropy source pkcs11
```

It's not immediately obvious which sources were properly initialized and which weren't.

1. Messages belonging to the same source are separated by a newline.

   `Enabling JITTER rng support` belongs to `Initializing entropy source jitter`
    but do `Initializing entropy source hwrng`, `Enabling RDSEED rng support` and `Initializing entropy source rdrand` all belong together?

    I'd suggest to group them together or add a prefix like `Jitter source: Enabling JITTER rng support`.

2. When initialization is successful, it would be nice to have a `Successfully initialized entropy source jitter` message.

Do I assume correctly, that my output means:
- RDRAND was initialized (first three lines)
- Jitter was initialized and pkcs11 failed

But what does `Initializing AES buffer` mean? To which source does it belong?

Another question: Why does `Initializing available sources` try to initialize pkcs11 which later notices it's not available? I guess `available` means rngd was compiled with support for it?
I'd suggest to change the wording of either phrase to distinguish the different usages of the word "available". What do you think?

**Comment by nhorman** [comment]
https://github.com/nhorman/rng-tools/tree/logging_cleanup

Try that branch out and let me know what you think.

as for the PKCS11 question, the error occurs because support for the soruce is built in to rngd, but it relies on the libp11 library, which is dynamically loaded (i.e. its not bound at link time), so while rngd supports it, it may not be available on a given system.

**Comment by JohnAZoidberg** [comment]
Oh yes, that's nice!
One nitpick: It'd be awesome if the prefixes were all the same length. Now `hwrng` is shorter than the others.

```diff
 Initializing available sources
-[hwrng]: Initialized
+[hwrng]: Initialized
 [rdrand]:Enabling RDSEED rng support
 [rdrand]:Initialized
 [jitter]:Initializing AES buffer
 [jitter]:Enabling JITTER rng support
 [jitter]:Initialized
 [pkcs11]:No pkcs11 slots available
 [pkcs11]:Initialization Failed
```

Like this, but maybe even put a space after every colon.

**Comment by JohnAZoidberg** [comment]
About pkcs11:
My error is `No pkcs11 slots available` so that means, by looking at the code, the library was found but it cannot find any slots.
That makes sense, since I don't have any smart card.

Now I've tried to set up a virtual one with softhsm but this doesn't seem to be found either:

```
$ softhsm2-util --init-token --slot 0 --label foobar
=== SO PIN (4-255 characters) ===
Please enter SO PIN: ****
Please reenter SO PIN: ****
=== User PIN (4-255 characters) ===
Please enter user PIN: ****
Please reenter user PIN: ****
The token has been initialized and is reassigned to slot 22379909
$ sudo rngd -f
Initializing available sources
[hwrng]:Initialized
[rdrand]:Enabling RDSEED rng support
[rdrand]:Initialized
[jitter]:Initializing AES buffer
[jitter]:Enabling JITTER rng support
[jitter]:Initialized
[pkcs11]:No pkcs11 slots available
[pkcs11]:Initialization Failed
```

Do you know what that could be? Should I open a new issue?

**Comment by nhorman** [comment]
what do you get if you run pkcs11-tool -L in your environment with the softhsm setup?

**Comment by nhorman** [comment]
Note, by default the pkcs11 entropy source uses the opensc-pkcs11 module.  If you want to use it with a software token, you likely need to specify the softhsm module with the engine_path config option, i.e.:
rngd -f -O pkcs11:engine_path:/usr/lib64/softhsm/libsofthsm.so

That worked fine for me

**Comment by JohnAZoidberg** [comment]
Yes, that works, thanks!
```
Initializing available sources
[hwrng]:Initialized
[rdrand]:Enabling RDSEED rng support
[rdrand]:Initialized
[jitter]:Initializing AES buffer
[jitter]:Enabling JITTER rng support
[jitter]:Initialized
[pkcs11]:Slot manufacturer......: SoftHSM project
[pkcs11]:Slot description......: SoftHSM slot ID 0x1557d85
[pkcs11]:Slot token label......: foobar
[pkcs11]:Slot token manufacturer......: SoftHSM project
[pkcs11]:Slot token model......: SoftHSM v2
[pkcs11]:Slot token serial......: 110014cf01557d85
[pkcs11]:Initialized
```

**Comment by JohnAZoidberg** [comment]
Then it'd be nice to have the slot information lines line up

```
[pkcs11]: Slot manufacturer.........: SoftHSM project
[pkcs11]: Slot description..........: SoftHSM slot ID 0x1557d85
[pkcs11]: Slot token label..........: foobar
[pkcs11]: Slot token manufacturer...: SoftHSM project
[pkcs11]: Slot token model..........: SoftHSM v2
[pkcs11]: Slot token serial.........: 110014cf01557d85
```

**Comment by nhorman** [comment]
I've updated the alignment and opened a pull request here:
https://github.com/nhorman/rng-tools/pull/76

**Comment by nhorman** [comment]
Merged
