### ISSUE TITLE
rngd ignores SIGTERM SIGINT

### ISSUE THREAD

**Issue by Thinstation** [nhorman/rng-tools#82]
sending rngd the SIGTERM or SIGINT signals does nothing. The daemon continues to run. Only SIGUSR1 effectively terminates the service.

**Comment by nhorman** [comment]
[root@hmswarspite nhorman]# at now + 1 minute
warning: commands will be executed using /bin/sh
at> kill `pidof -SIGTERM rngd`
at> <EOT>
job 13 at Thu Feb 13 06:41:00 2020
[root@hmswarspite nhorman]# rngd -f -d
Initializing available sources
[hwrng ]: read error
[hwrng ]: no available rng device
[hwrng ]: Initialization Failed
[rdrand]: Enabling RDSEED rng support
[rdrand]: Initialized
[jitter]: JITTER starts 4 threads
[jitter]: JITTER thread on cpu 0 wakes up for refill
[jitter]: JITTER thread on cpu 1 wakes up for refill
[jitter]: CPU Thread 0 is ready
[jitter]: CPU Thread 1 is ready
[jitter]: JITTER thread on cpu 3 wakes up for refill
[jitter]: JITTER thread on cpu 2 wakes up for refill
[jitter]: CPU Thread 2 is ready
[jitter]: CPU Thread 3 is ready
[jitter]: Initializing AES buffer
[jitter]: xread_jitter requests 16 bytes from pipe
[jitter]: failed read: Resource temporarily unavailable
[jitter]: xread_jitter requests 16 bytes from pipe
[jitter]: failed read: Resource temporarily unavailable
[jitter]: Unable to obtain AES key, disabling AES in JITTER source
[jitter]: xread_jitter requests 16535 bytes from pipe
[jitter]: failed read: Resource temporarily unavailable
[jitter]: xread_jitter requests 16535 bytes from pipe
[jitter]: failed read: Resource temporarily unavailable
[jitter]: Enabling JITTER rng support
[jitter]: xread_jitter requests 4 bytes from pipe
[jitter]: failed read: Resource temporarily unavailable
[jitter]: xread_jitter requests 4 bytes from pipe
[jitter]: failed read: Resource temporarily unavailable
[jitter]: xread_jitter requests 4 bytes from pipe
[jitter]: failed read: Resource temporarily unavailable
[jitter]: xread_jitter requests 4 bytes from pipe
[jitter]: failed read: Resource temporarily unavailable
[jitter]: Initialized
[pkcs11]: No pkcs11 slots available
[pkcs11]: Initialization Failed
Reading entropy from Intel RDRAND Instruction RNG
Added 3816/4096 bits entropy
Added 3843/4096 bits entropy
Added 3866/4096 bits entropy
Added 3888/4096 bits entropy
Added 3907/4096 bits entropy
Added 3925/4096 bits entropy
Added 3941/4096 bits entropy
Added 3955/4096 bits entropy
Added 3968/4096 bits entropy
Added 3980/4096 bits entropy
Added 3991/4096 bits entropy
Added 4001/4096 bits entropy
Added 4010/4096 bits entropy
Added 4018/4096 bits entropy
Added 4025/4096 bits entropy
Added 4031/4096 bits entropy
Added 4037/4096 bits entropy
Pool full at 4096, sleeping!
[jitter]: jent_read_entropy time on cpu 3 is 2.005954076000e+00 sec
[jitter]: Writing to pipe
[jitter]: DONE Writing to pipe with return 16535
[jitter]: JITTER thread on cpu 3 wakes up for refill
[jitter]: jent_read_entropy time on cpu 0 is 2.011476013000e+00 sec
[jitter]: Writing to pipe
[jitter]: DONE Writing to pipe with return 16535
[jitter]: JITTER thread on cpu 0 wakes up for refill
[jitter]: jent_read_entropy time on cpu 1 is 2.010690220000e+00 sec
[jitter]: Writing to pipe
[jitter]: DONE Writing to pipe with return 16535
[jitter]: JITTER thread on cpu 1 wakes up for refill
[jitter]: jent_read_entropy time on cpu 2 is 2.008117192000e+00 sec
[jitter]: Writing to pipe
[jitter]: DONE Writing to pipe with return 16535
[jitter]: JITTER thread on cpu 2 wakes up for refill
[jitter]: jent_read_entropy time on cpu 1 is 1.003840865000e+00 sec
[jitter]: Writing to pipe
[jitter]: DONE Writing to pipe with return 16535
[jitter]: JITTER thread on cpu 1 wakes up for refill
[jitter]: jent_read_entropy time on cpu 0 is 1.000975638000e+00 sec
[jitter]: Writing to pipe
[jitter]: DONE Writing to pipe with return 16535
[jitter]: JITTER thread on cpu 0 wakes up for refill
[jitter]: jent_read_entropy time on cpu 3 is 2.004683429000e+00 sec
[jitter]: Writing to pipe
[jitter]: DONE Writing to pipe with return 16535
[jitter]: JITTER thread on cpu 3 wakes up for refill
[jitter]: jent_read_entropy time on cpu 2 is 2.005118324000e+00 sec
[jitter]: Writing to pipe
[jitter]: jent_read_entropy time on cpu 1 is 2.006729171000e+00 sec
[jitter]: Writing to pipe
[jitter]: jent_read_entropy time on cpu 0 is 2.006979893000e+00 sec
[jitter]: Writing to pipe
[jitter]: jent_read_entropy time on cpu 3 is 2.010991164000e+00 sec
[jitter]: Writing to pipe
[rdrand]: Shutting down
[jitter]: Shutting down
[jitter]: Checking on done for thread 0
[jitter]: Closing thread 0
[jitter]: Checking on done for thread 1
[jitter]: Closing thread 1
[jitter]: Checking on done for thread 2
[jitter]: Closing thread 2
[jitter]: Checking on done for thread 3
[jitter]: Closing thread 3


Seems like SIGTERM is properly terminating rngd to me.  Can you be more descriptive about the problem you are having?

**Comment by Thinstation** [comment]
The exact problem I'm having is that when a system is shutting down, systemd sends the SIGTERM signal to rngd, but rngd does not die. When I use your debug command, and run rngd in the foreground, it does die on SIGTERM. Why not when running in daemon mode?

**Comment by nhorman** [comment]
what version of rng-tools are you running?

**Comment by Thinstation** [comment]
6.7

**Comment by nhorman** [comment]
There are a few patches that went into 6.8 that fixed some termination issues with rngd (3e47faae108df4824531bf9c003cc1c65b7b2842 and 62aa34f8f8a567b99b03079aebda8bac71c334bd).  I sugest you build the head of the tree and see if the problem persists

**Comment by Doncuppjr** [comment]
Still no.....

ts_525400123456:~# ps x |grep -e rngd
 4570 root      0:00 /sbin/rngd -W 50% -p /run/rngd.pid
 5567 root      0:00 grep -e rngd
ts_525400123456:~# rngd -v
rngd 6.8
Copyright 2001-2004 Jeff Garzik
Copyright 2017 Neil Horman
Copyright (c) 2001 by Philipp Rumpf
This is free software; see the source for copying conditions.  There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ts_525400123456:~# kill -SIGTERM `pidof rngd`
ts_525400123456:~# pidof rngd
4570
ts_525400123456:~# kill -SIGINT `pidof rngd`
ts_525400123456:~# pidof rngd
4570
ts_525400123456:~# kill -SIGUSR1 `pidof rngd`
ts_525400123456:~# pidof rngd
ts_525400123456:~#

**Comment by nhorman** [comment]
sorry, I should have been more clear, when I said the head of the git tree, I meant the head of the git tree, not 6.8.  The second of those two fixes went it a few commits after 6.8 was released.
