### ISSUE TITLE
[rdrand]: Initialization Failed

### ISSUE THREAD

**Issue by Mingli-Yu** [nhorman/rng-tools#83]
# rpm -qa|grep rng-tools
rng-tools-6.9-r0.core2_64

# systemctl status rngd
* rngd.service - Hardware RNG Entropy Gatherer Daemon
     Loaded: loaded (/lib/systemd/system/rngd.service; enabled; vendor preset: >
     Active: active (running) since Tue 2020-02-25 05:08:11 UTC; 42min ago
   Main PID: 133 (rngd)
      Tasks: 2 (limit: 3591)
     Memory: 1.0M
     CGroup: /system.slice/rngd.service
             `-133 /usr/sbin/rngd -f -r /dev/hwrng

Feb 25 05:08:14 qemux86-64 rngd[133]: Initializing available sources
Feb 25 05:08:14 qemux86-64 rngd[133]: [hwrng ]: Initialized
Feb 25 05:08:14 qemux86-64 rngd[133]: [rdrand]: Initialization Failed
Feb 25 05:08:14 qemux86-64 rngd[133]: [jitter]: Initializing AES buffer
Feb 25 05:08:31 qemux86-64 rngd[133]: [jitter]: Enabling JITTER rng support
Feb 25 05:08:39 qemux86-64 rngd[133]: [jitter]: Initialized
Warning: Journal has been rotated since unit was started. Log output is incompl

**Comment by Mingli-Yu** [comment]
It breaks here.
if (!(info.ecx & features_ecx1_rdrand))
                return 1;

**Comment by nhorman** [comment]
Thats working as designed.  If that check fails it indicates that your cpu doesn't support, or isn't exposing the rdrand instruction, and so the rdrand entropy source cannot work

**Comment by Mingli-Yu** [comment]
Thanks very much for your info, then how to make the cpu support the function as I run the service in qemu env.
And as the message indicates "[rdrand]: Initialization Failed", but the service started successfully via "systemctl status rngd".

**Comment by nhorman** [comment]
you probably cant enable rdrand.  If your hardware doesn't support the instruction, theres nothing you can do, and if it does, you will need access to the host so as to run your hypervisor process with the appropriate rdrand cpu flag enabled.

However, its important to note that this isn't in and of itself a problem.  rngd supports several different entropy sources, of which rdrand is only one.  You have other sources (specficially jitter) which is operational, and so allows rngd to function properly.  The failure to initalize rdrand isn't fatal to your operation.

**Comment by Mingli-Yu** [comment]
Thanks nhorman very much for your explanation!
Through the rngd status as below, the rdrand doesn't work as it indicates "Initialization Failed", but at least one entropy source such jitter works, so the rngd works as expected though one message "[rdrand]: Initialization Failed".
 # systemctl status rngd

    rngd.service - Hardware RNG Entropy Gatherer Daemon
    Loaded: loaded (/lib/systemd/system/rngd.service; enabled; vendor preset: >
    Active: active (running) since Tue 2020-02-25 05:08:11 UTC; 42min ago
    Main PID: 133 (rngd)
    Tasks: 2 (limit: 3591)
    Memory: 1.0M
    CGroup: /system.slice/rngd.service
    `-133 /usr/sbin/rngd -f -r /dev/hwrng

Feb 25 05:08:14 qemux86-64 rngd[133]: Initializing available sources
Feb 25 05:08:14 qemux86-64 rngd[133]: [hwrng ]: Initialized
Feb 25 05:08:14 qemux86-64 rngd[133]: [rdrand]: Initialization Failed
Feb 25 05:08:14 qemux86-64 rngd[133]: [jitter]: Initializing AES buffer
Feb 25 05:08:31 qemux86-64 rngd[133]: [jitter]: Enabling JITTER rng support
Feb 25 05:08:39 qemux86-64 rngd[133]: [jitter]: Initialized
Warning: Journal has been rotated since unit was started. Log output is incompl

**Comment by Mingli-Yu** [comment]
https://github.com/nhorman/rng-tools/pull/84
