### ISSUE TITLE
rngd_jitter: AES initialization only works because of invalid fcntl

### ISSUE THREAD

**Issue by schiffermtq** [nhorman/rng-tools#98]
With only the jitter source available, we're seeing nondeterministic startup behaviour:
- In some cases, rngd will hang briefly after the message "Initializing AES buffer" (and "xread_jitter requests 16 bytes from pipe" with `--debug`), but then continue and run as expected
- In other cases, instead of hanging, the AES key generation will fail immediately:
```
[jitter]: Initializing AES buffer
[jitter]: xread_jitter requests 16 bytes from pipe
[jitter]: failed read: Resource temporarily unavailable
[jitter]: xread_jitter requests 16 bytes from pipe
[jitter]: failed read: Resource temporarily unavailable
[jitter]: Unable to obtain AES key, disabling AES in JITTER source
```
In the second case, rngd will then spam the message "Entropy Generation is slow, consider tuning/adding sources" for a few seconds.

It turned out that this nondeterministic behaviour is caused by an incorrect fcntl, fixed by the following patch:
```diff
--- a/rngd_jitter.c
+++ b/rngd_jitter.c
@@ -449,7 +449,7 @@ int init_jitter_entropy_source(struct rng *ent_src)
 
 	flags = fcntl(pipefds[0], F_GETFL, 0);
 	flags |= O_NONBLOCK;
-	fcntl(pipefds[0], F_SETFL, &flags);
+	fcntl(pipefds[0], F_SETFL, flags);
 
 	if (ent_src->rng_options[JITTER_OPT_USE_AES].int_val) {
 		/*
```
This sets various random flags on the pipefd - in particular O_NONBLOCK was often not actually set, which can be seen using strace.

The above patch fixes the fcntl to its intended effect, but by doing so, it makes the AES key generation fail consistently: The initial `jent_read_entropy()` takes roughly 6.5 seconds on my test system, so with O_NONBLOCK set, reading from the entropy pipe will always fail.

**Comment by nhorman** [comment]
Yeah, that looks right.  Open a PR with the change please, and I'll merge it

**Comment by nhorman** [comment]
the change to set O_NONBLOCK looks correct, so we should probably make that change.  We also need to move the setting of O_NONBLOCK to below the initialization of the aes key.  I.e. we want to do blocking reads while we set that up, and then switch to non-blocking reads for the rngd requests post init.  If you open a PR for this with those changes, I'll merge it.

**Comment by schiffermtq** [comment]
Should we also do something about the case where AES is disabled explicitly? There will still be "Entropy Generation is slow, consider tuning/adding sources" spam during the initial entropy feeding in this case, until the initial `jent_read_entropy()` has finished. This could be worked around by adding a single `xread_jitter()` before setting O_NONBLOCK in the !AES case as well.

I've found one downside of blocking during initialization until there is enough entropy: `rngd -l` will also take a few seconds.

I can open a PR with these changes if the tradeoffs are acceptable.

**Comment by nhorman** [comment]
Yes, the tradeoffs seem acceptable to me.  As for the log spamming, I'm not sure what to do there.  Jitter as a source simply is slow (it can take many seconds on a slow cpu to generate entropy at any given time).  Its meant to be used on virtual systems without other entropy sources.  We could ratelimit the entropy generation is slow message just to avoid the spam, but it won't do much for the root problem, which is that jitter is a slow source of entropy
